# -*- coding: utf-8 -*-
# flake8: noqa
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - 审计中心 (BlueKing - Audit Center) available.
Copyright (C) 2023 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.
We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""

# Base
PAGE = 1
PAGE_SIZE = 10

META_QUERY_PARAMS = {
    "share_uid": "just_test",
    "type": "dashboard",
    "xo[tt]": "pp",
}
META_QUERY_RESPONSE = {
    "result": True,
    "code": 200,
    "data": {
        "type": "dashboard",
        "data": {
            "id": 14745,
            "created_time": "2024-11-05 11:28:24",
            "updated_time": "2025-03-05 13:34:36",
            "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
            "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
            "dashboard_title": "审计中心风险视图（全风险）",
            "parent_version": "V80",
            "version": "V81",
            "description": "",
            "panels": [
                {
                    "uid": "bk-c5576024-49b1054b-6f9853c6",
                    "mode": "layout",
                    "type": "row",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "metrics": [],
                        "is_linked": False,
                        "raw_query": False,
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "",
                        "link_fields": [],
                        "query_mode": "simple",
                        "time_compare": [],
                        "need_time_compare": False,
                    },
                    "title": "关键指标",
                    "panels": [],
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": ""},
                    "filters": [],
                    "gridPos": {
                        "h": 3,
                        "i": "bk-c5576024-49b1054b-6f9853c6",
                        "w": 100,
                        "x": 0,
                        "y": 0,
                        "maxH": 3,
                        "maxW": 100,
                        "minH": 3,
                        "minW": 100,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "layout",
                    "collapsed": False,
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": "#313238"},
                            "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "#fff",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "description": "",
                    "privateAttrs": {},
                    "dashboard_uid": "3tgECXYxBuSpLzo9Zyc7Dj",
                },
                {
                    "uid": "4tJ44mxwu5PpPgTVSUJusT",
                    "mode": "action",
                    "type": "selector",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "params": "",
                        "metrics": [],
                        "is_linked": False,
                        "raw_query": False,
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_mode": "simple",
                        "query_text": "",
                        "link_fields": [],
                        "process_code": "",
                        "time_compare": [],
                        "time_dimensions": {},
                        "need_time_compare": False,
                    },
                    "title": "选择接入系统",
                    "panels": [],
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": ""},
                    "filters": [],
                    "gridPos": {
                        "h": 7,
                        "i": "4tJ44mxwu5PpPgTVSUJusT",
                        "w": 25,
                        "x": 0,
                        "y": 0,
                        "maxH": 370,
                        "maxW": 100,
                        "minH": 3,
                        "minW": 8,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Action",
                    "collapsed": False,
                    "space_uid": "ZHxssS5Pzrm6GaUrRbWLEH",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": ""},
                            "sub_title": {"show": False, "align": "start", "color": ""},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {
                            "color": "",
                            "style": "none",
                            "width": 1,
                            "radius": 0,
                            "padding": [16, 16, 16, 16],
                            "isCustomPadding": False,
                        },
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "sql": "",
                        "flag": "system_id",
                        "json": [{"label": "x", "value": "o"}],
                        "type": "table",
                        "field": {
                            "id": 39145,
                            "uid": "Fid2LnmbPWsBhwnKdF3Zm6",
                            "name": "id",
                            "type": "string",
                            "table": None,
                            "remark": "",
                            "map_uid": "",
                            "raw_name": "id",
                            "data_type": "dimension",
                            "is_joined": None,
                            "is_virtual": False,
                            "dataset_uid": "3pGiWyjJ6XPyfPMiAcVfuS",
                            "display_name": "实例ID",
                        },
                        "scope": [
                            {
                                "field": {
                                    "uid": "bk-5e43d62e-cf198f41-d9d43091",
                                    "remark": "",
                                    "map_uid": "",
                                    "aggregate": None,
                                    "is_joined": False,
                                    "is_virtual": False,
                                },
                                "panel_uid": [],
                                "select_all": False,
                                "dataset_uid": "",
                                "datasource_uid": "",
                            }
                        ],
                        "layout": "vertical",
                        "add_all": False,
                        "default": "o",
                        "multiple": False,
                        "dataset_uid": "3pGiWyjJ6XPyfPMiAcVfuS",
                        "defaultType": "specify",
                        "label_field": {
                            "id": 39147,
                            "uid": "33wJiyYFN4TvcKiMenVKGA",
                            "name": "display_name",
                            "type": "string",
                            "table": None,
                            "remark": "",
                            "map_uid": "",
                            "raw_name": "display_name",
                            "data_type": "dimension",
                            "is_joined": None,
                            "is_virtual": False,
                            "dataset_uid": "3pGiWyjJ6XPyfPMiAcVfuS",
                            "display_name": "实例名称",
                        },
                        "select_first": False,
                        "datasource_uid": "cv6ANd7kU6tVnrANvRusAQ",
                        "defaultDynamic": 1,
                    },
                    "description": "选择系统",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "id": 19760,
                    "created_time": "2025-03-20 20:58:35",
                    "updated_time": "2025-03-20 21:00:37",
                    "dashboard_uid": "xJhJXMyWBUmNr5Xcm3rayj",
                    "father_uid": "",
                    "child_panels": [],
                    "dataId": "",
                    "data": {},
                },
                {
                    "uid": "4R6sIGxga0xMeK6LQy5IUO",
                    "mode": "action",
                    "type": "selector",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "metrics": [],
                        "is_linked": False,
                        "raw_query": False,
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "",
                        "link_fields": [],
                        "time_compare": [],
                        "need_time_compare": False,
                        "query_mode": "simple",
                    },
                    "title": "场景",
                    "dataId": "uv67pjf0w6",
                    "panels": [],
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": ""},
                    "filters": [],
                    "gridPos": {
                        "h": 7,
                        "i": "4R6sIGxga0xMeK6LQy5IUO",
                        "w": 25,
                        "x": 12,
                        "y": 3,
                        "maxH": 370,
                        "maxW": 100,
                        "minH": 3,
                        "minW": 17,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Action",
                    "collapsed": False,
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": ""},
                            "sub_title": {"show": False, "align": "start", "color": ""},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "sql": "",
                        "flag": "tag",
                        "json": [],
                        "type": "table",
                        "field": {
                            "uid": "bk-4df78584-da1fc153-1f9193fd",
                            "remark": "",
                            "map_uid": "",
                            "aggregate": None,
                            "is_joined": False,
                            "is_virtual": False,
                        },
                        "scope": [
                            {
                                "field": {
                                    "uid": "bk-4a8c6c0b-fc95d83d-5c3f6fd4",
                                    "remark": "",
                                    "map_uid": "",
                                    "aggregate": None,
                                    "is_joined": False,
                                    "is_virtual": False,
                                },
                                "panel_uid": [],
                                "select_all": False,
                                "dataset_uid": "",
                                "datasource_uid": "",
                            }
                        ],
                        "layout": "vertical",
                        "add_all": True,
                        "default": 1,
                        "map_uid": "3Rqy8vYJ9q6CF4RYPmCwpY",
                        "multiple": True,
                        "select_first": False,
                        "datasource_uid": "",
                    },
                    "description": "",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
                },
                {
                    "uid": "3JMaxL2RPJvnDFwdG3NPFE",
                    "mode": "action",
                    "type": "time-ranger",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "metrics": [],
                        "is_linked": False,
                        "raw_query": False,
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "",
                        "link_fields": [],
                        "time_compare": [],
                        "need_time_compare": False,
                        "query_mode": "simple",
                    },
                    "title": "时间范围选择器",
                    "dataId": "i2ij5m4l5p",
                    "panels": [],
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": ""},
                    "filters": [],
                    "gridPos": {
                        "h": 7,
                        "i": "3JMaxL2RPJvnDFwdG3NPFE",
                        "w": 25,
                        "x": 64,
                        "y": 3,
                        "maxH": 370,
                        "maxW": 100,
                        "minH": 3,
                        "minW": 17,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Action",
                    "collapsed": False,
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": "#313238"},
                            "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "#fff",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "flag": "dtEventTime",
                        "range": [],
                        "scope": [
                            {
                                "field": {
                                    "uid": "bk-a39597b9-43221bdd-33319ba7",
                                    "remark": "",
                                    "map_uid": "",
                                    "aggregate": None,
                                    "is_joined": False,
                                    "is_virtual": False,
                                },
                                "panel_uid": [],
                                "select_all": False,
                                "dataset_uid": "",
                                "datasource_uid": "",
                            }
                        ],
                        "layout": "vertical",
                        "default": ["now-7d", "now"],
                        "rangeType": "year",
                        "rangeNumber": 1,
                        "isLimitRange": False,
                    },
                    "description": "",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
                },
                {
                    "uid": "SG38mn5dmHbUTKzCYLRNTM",
                    "mode": "chart",
                    "type": "rich-text",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "metrics": [],
                        "is_linked": False,
                        "raw_query": False,
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "",
                        "link_fields": [],
                        "time_compare": [],
                        "need_time_compare": False,
                        "query_mode": "simple",
                    },
                    "title": "-",
                    "dataId": "ds9w4ojpuz",
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": ""},
                    "filters": [],
                    "gridPos": {
                        "h": 11,
                        "i": "SG38mn5dmHbUTKzCYLRNTM",
                        "w": 100,
                        "x": 0,
                        "y": 10,
                        "maxH": 10000,
                        "maxW": 100,
                        "minH": 3,
                        "minW": 13,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Media",
                    "collapsed": False,
                    "data_type": "row",
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": False, "align": "start", "color": "#313238"},
                            "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "#fff",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "content": "<p style=\"text-align: left; line-height: 1;\"><span style=\"font-size: 22px;\"><strong>风险总数</strong></span></p><p style=\"text-align: left; line-height: 1;\"><em>数据说明：今日新增风险数为今日数据，不随顶部顶部数据选中变化；总风险数（选中时间内）为当前选中的时间内的新增风险数，可通过选择时间来看某段时间内的，同时影响新增风险事件数的趋势。</em></p>",
                        "mapping": {"list": []},
                        "mapValueHoverPoint": False,
                    },
                    "description": "",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
                },
                {
                    "uid": "agspBMjoj82jyoVSekySfb",
                    "mode": "chart",
                    "type": "trending-chart",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "format": "point",
                        "metrics": [
                            {
                                "uid": "bk-fccc4d1f-a4181ea4-e986df62",
                                "name": "当日新增风险数",
                                "type": "",
                                "remark": "",
                                "map_uid": "",
                                "aggregate": None,
                                "is_joined": False,
                                "is_virtual": False,
                                "display_name": "当日新增风险数",
                            }
                        ],
                        "is_linked": False,
                        "raw_query": True,
                        "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                        "variation": [],
                        "dimensions": [
                            {
                                "uid": "bk-c1d18518-e2d55795-075edc48",
                                "name": "日期",
                                "type": "",
                                "remark": "",
                                "map_uid": "",
                                "aggregate": None,
                                "is_joined": False,
                                "is_virtual": False,
                                "display_name": "日期",
                            }
                        ],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "select date_format(FROM_UNIXTIME(event_time/1000000), '%Y-%m-%d')  as `日期`, count(distinct risk_id) as `当日新增风险数` from 5000448_dwd_bkaudit_risk_ticket_df\nwhere {{dtEventTime}}(dtEventTime) and {{dept_name}}(dept_name) and {{tag}}(tag) and   {{dtEventTime.format('%s')}}(event_time/1000000)\ngroup by 1\n order by 1\nlimit 1000",
                        "link_fields": [],
                        "need_sample": False,
                        "time_compare": [],
                        "need_time_compare": False,
                        "query_mode": "sql",
                    },
                    "title": "当日新增风险数",
                    "dataId": "kl38n9cl4r",
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": "3Xof5rxGtBw9LoXUTck6V4"},
                    "filters": [],
                    "gridPos": {
                        "h": 37,
                        "i": "agspBMjoj82jyoVSekySfb",
                        "w": 25,
                        "x": 0,
                        "y": 21,
                        "maxH": 10000,
                        "maxW": 100,
                        "minH": 7,
                        "minW": 13,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Gauge",
                    "collapsed": False,
                    "data_type": "row",
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "环比",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": "#313238"},
                            "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "#fff",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "visual": {
                            "suffix": "",
                            "metricColor": "#313238",
                            "yAxiStarter": 0,
                            "isShowMetric": True,
                            "metricFontSize": 24,
                            "compareInterval": 1,
                            "isPositiveGreen": True,
                            "isShowTrendIcon": True,
                            "yAxiStarterAuto": False,
                            "isShowComparison": True,
                            "isShowTrendChart": True,
                            "customColumnSettings": [
                                {
                                    "field": "tips",
                                    "日期": "",
                                    "column1": "列提示",
                                    "column2": "",
                                    "_X_ROW_KEY": "row_215",
                                    "当日新增风险数": "",
                                },
                                {
                                    "field": "colWidth",
                                    "日期": "auto",
                                    "column1": "样式",
                                    "column2": "列宽",
                                    "_X_ROW_KEY": "row_216",
                                    "当日新增风险数": "auto",
                                },
                                {
                                    "field": "align",
                                    "日期": "left",
                                    "column1": "",
                                    "column2": "对齐方式",
                                    "_X_ROW_KEY": "row_217",
                                    "当日新增风险数": "left",
                                },
                                {
                                    "field": "autoWrap",
                                    "日期": False,
                                    "column1": "",
                                    "column2": "自动换行",
                                    "_X_ROW_KEY": "row_218",
                                    "当日新增风险数": False,
                                },
                                {
                                    "field": "showFilter",
                                    "日期": False,
                                    "column1": "功能",
                                    "column2": "列筛选",
                                    "_X_ROW_KEY": "row_219",
                                    "当日新增风险数": False,
                                },
                                {
                                    "field": "showSort",
                                    "日期": False,
                                    "column1": "",
                                    "column2": "列排序",
                                    "_X_ROW_KEY": "row_220",
                                    "当日新增风险数": False,
                                },
                            ],
                        },
                        "mapping": {"list": []},
                        "numberDisplayRules": [
                            {
                                "color": "#000000",
                                "metrics": [],
                                "fontSize": 32,
                                "numberUnit": "",
                                "decimalPlaces": 0,
                                "needTransform": False,
                                "transformRule": "normal",
                            }
                        ],
                    },
                    "description": "",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
                },
                {
                    "uid": "mUNXHeWC9KvkJM7ukUd79C",
                    "mode": "chart",
                    "type": "number-panel",
                    "query": {
                        "limit": {"size": 1000, "offset": None},
                        "order": [],
                        "where": [],
                        "format": "row",
                        "metrics": [
                            {
                                "uid": "bk-3a9dc45d-f37f491e-de09322f",
                                "name": "总风险数",
                                "type": "",
                                "remark": "",
                                "map_uid": "",
                                "aggregate": None,
                                "is_joined": False,
                                "is_virtual": False,
                                "display_name": "总风险数",
                            }
                        ],
                        "is_linked": False,
                        "raw_query": True,
                        "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                        "variation": [],
                        "dimensions": [],
                        "drill_down": [],
                        "is_drilled": False,
                        "query_text": "select count(distinct risk_id) as `总风险数` from 5000448_dwd_bkaudit_risk_ticket_df\nwhere {{dtEventTime}}(dtEventTime) and  {{dept_name}}(dept_name) and {{tag}}(tag)  \nand {{dtEventTime.format('%s')}}(event_time/1000000)\n \nlimit 1000",
                        "link_fields": [],
                        "need_sample": False,
                        "time_compare": [],
                        "need_time_compare": False,
                        "query_mode": "sql",
                    },
                    "title": "新增风险总数（选中时间内）",
                    "dataId": "kr3dx2qd7b",
                    "dataset": {"db_type": None, "dataset_uid": "", "datasource_uid": "3Xof5rxGtBw9LoXUTck6V4"},
                    "filters": [],
                    "gridPos": {
                        "h": 37,
                        "i": "mUNXHeWC9KvkJM7ukUd79C",
                        "w": 25,
                        "x": 25,
                        "y": 21,
                        "maxH": 10000,
                        "maxW": 100,
                        "minH": 7,
                        "minW": 13,
                        "moved": False,
                    },
                    "build_in": True,
                    "category": "Gauge",
                    "collapsed": False,
                    "data_type": "row",
                    "space_uid": "YPJYDtbeaV2rmjwt34n6iQ",
                    "sub_title": "",
                    "chartStyle": {
                        "info": {
                            "title": {"show": True, "align": "start", "color": "#313238"},
                            "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                            "description": {"show": False, "align": "start", "color": "#ffffff"},
                        },
                        "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                        "background": {
                            "url": "",
                            "size": "contain",
                            "color": "#fff",
                            "bgType": "local",
                            "repeat": "no-repeat",
                            "opacity": 30,
                            "localUrl": "",
                            "position": "center",
                            "isShowBgImg": False,
                        },
                    },
                    "chartConfig": {
                        "visual": {
                            "isMom": False,
                            "isYoy": False,
                            "units": [],
                            "interval": 40,
                            "isShowText": True,
                            "noDataText": "NoData",
                            "metricColor": "",
                            "noDataColor": "#ff0000",
                            "metricFontSize": 24,
                            "noDataFontSize": 64,
                            "customColumnSettings": [
                                {"field": "tips", "column1": "列提示", "column2": "", "_X_ROW_KEY": "row_215", "总风险数": ""},
                                {
                                    "field": "colWidth",
                                    "column1": "样式",
                                    "column2": "列宽",
                                    "_X_ROW_KEY": "row_216",
                                    "总风险数": "auto",
                                },
                                {
                                    "field": "align",
                                    "column1": "",
                                    "column2": "对齐方式",
                                    "_X_ROW_KEY": "row_217",
                                    "总风险数": "left",
                                },
                                {
                                    "field": "autoWrap",
                                    "column1": "",
                                    "column2": "自动换行",
                                    "_X_ROW_KEY": "row_218",
                                    "总风险数": False,
                                },
                                {
                                    "field": "showFilter",
                                    "column1": "功能",
                                    "column2": "列筛选",
                                    "_X_ROW_KEY": "row_219",
                                    "总风险数": False,
                                },
                                {
                                    "field": "showSort",
                                    "column1": "",
                                    "column2": "列排序",
                                    "_X_ROW_KEY": "row_220",
                                    "总风险数": False,
                                },
                            ],
                        },
                        "mapping": {"list": []},
                        "numberDisplayRules": [],
                    },
                    "description": "",
                    "privateAttrs": {},
                    "advanceConfig": {},
                    "dashboard_uid": "3ADcXmBPkg533v8ZS6mQX2",
                },
            ],
            "colors": {},
            "style": {
                "info": {
                    "title": {"show": True, "align": "start", "color": "#313238"},
                    "sub_title": {"show": False, "align": "start", "color": "#979BA5"},
                    "description": {"show": False, "align": "start", "color": "#ffffff"},
                },
                "border": {"color": "#000", "style": "none", "width": 1, "radius": 0},
                "background": {
                    "url": "",
                    "size": "contain",
                    "color": "#fff",
                    "bgType": "local",
                    "repeat": "no-repeat",
                    "opacity": 30,
                    "localUrl": "",
                    "position": "center",
                    "isShowBgImg": False,
                },
            },
            "variables": [],
            "actionMapPanelRelation": {
                "--3Nqvgswoa1haJuGMYcgYOp": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--3nC8DYTQnhngK3uvYq3KKb": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--6l2U7TdRiBhU3ealaYLe0p": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--8zXLFTuSNyrCOgp425Tl9p": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--CHvMcxz6JHflgCyO42yNa7": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--E1rYnBKAPQZ3Tlj1fjuAp5": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--JJh63YUCmBZvpOzCoj7dzX": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--OEwERM7y5VWkVWy4LIihVK": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                },
                "--TgB124KqJVsExT95huwlQC": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--X9ayPBUks01vvIYgPrRcWH": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--agspBMjoj82jyoVSekySfb": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--azheFeSNI8p7GEoq7wongc": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--m7znkURCaV1Kho3BaA1l26": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--mUNXHeWC9KvkJM7ukUd79C": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--oflhUxMdwc98hnhvNyC2p9": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--qOvBjeyQOPJT2SYF46x0KD": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--qo98bqhfFjwmVmIajLCLvP": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--sKwj0qEaigaieru4waZ5L1": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
                "--zqbzz8BxMknuxHHYxSsY5j": {
                    "3JMaxL2RPJvnDFwdG3NPFE": {
                        "dtEventTime": {"flag": "dtEventTime", "type": "time-ranger", "value": ["now-7d", "now"]}
                    },
                    "3pnLr3ayoqXecvoH7KJkXa": {"dept_name": {"flag": "dept_name", "type": "selector", "value": ""}},
                    "4R6sIGxga0xMeK6LQy5IUO": {"tag": {"flag": "tag", "type": "selector", "value": ["人员"]}},
                },
            },
            "panel_links": [],
            "data": {"variables": [], "panel_links": [], "new_pos_version": True},
        },
        "filters": {
            "3JMaxL2RPJvnDFwdG3NPFE": ["now-30d", "now"],
            "4R6sIGxga0xMeK6LQy5IUO": 1,
            "3pnLr3ayoqXecvoH7KJkXa": "",
        },
        "constants": {},
        "panel_plugins": [],
        "datasource_plugins": [],
    },
    "message": None,
    "request_id": "",
    "trace_id": "",
}
CHECK_DATA = [{'name': 'a', 'value': 'A'}]
