# Generated by Django 4.2.23 on 2025-07-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0009_update_action_resource_type'),
        ('permission', '0009_update_action_resource_type_20250704'),
    ]

    operations = []
