# Generated by Django 4.2.23 on 2025-08-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0010_merge_20250723_1146'),
        ('permission', '0010_update_action_resource_type_20250808'),
    ]

    operations = []
