# Generated by Django 4.2.23 on 2025-08-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0011_merge_20250819_1112'),
        ('permission', '0011_update_action_resource_type_20250813'),
    ]

    operations = []
