# Generated by Django 4.2.26 on 2026-04-04 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('scene_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='场景ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='场景描述')),
                (
                    'status',
                    models.CharField(
                        choices=[('enabled', '启用'), ('disabled', '停用')],
                        db_index=True,
                        default='enabled',
                        max_length=32,
                        verbose_name='状态',
                    ),
                ),
                ('managers', models.JSONField(default=list, verbose_name='场景管理员列表')),
                ('users', models.JSONField(default=list, verbose_name='场景使用者列表')),
            ],
            options={
                'verbose_name': '审计场景',
                'verbose_name_plural': '审计场景',
                'ordering': ['-scene_id'],
            },
        ),
        migrations.CreateModel(
            name='ScenePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='报表名称')),
                (
                    'category',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('security_overview', '安全总览'),
                            ('behavior_analysis', '行为分析'),
                            ('data_security', '数据安全'),
                            ('compliance_audit', '合规审计'),
                            ('asset_security', '资产安全'),
                            ('operation_efficiency', '运营效率'),
                            ('threat_intelligence', '威胁情报'),
                            ('cloud_security', '云安全'),
                        ],
                        default='',
                        max_length=32,
                        verbose_name='分类',
                    ),
                ),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[('published', '已上架'), ('unpublished', '未上架')],
                        default='unpublished',
                        max_length=32,
                        verbose_name='状态',
                    ),
                ),
                (
                    'scope_type',
                    models.CharField(
                        choices=[('platform', '平台级'), ('scene', '场景级')],
                        db_index=True,
                        default='platform',
                        max_length=32,
                        verbose_name='归属级别',
                    ),
                ),
                ('scene_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='所属场景ID')),
            ],
            options={
                'verbose_name': '场景报表',
                'verbose_name_plural': '场景报表',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SceneTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='工具名称')),
                ('tool_type', models.CharField(blank=True, default='', max_length=32, verbose_name='工具类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='标签')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[('published', '已上架'), ('unpublished', '未上架')],
                        default='unpublished',
                        max_length=32,
                        verbose_name='状态',
                    ),
                ),
                (
                    'scope_type',
                    models.CharField(
                        choices=[('platform', '平台级'), ('scene', '场景级')],
                        db_index=True,
                        default='platform',
                        max_length=32,
                        verbose_name='归属级别',
                    ),
                ),
                ('scene_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='所属场景ID')),
            ],
            options={
                'verbose_name': '场景工具',
                'verbose_name_plural': '场景工具',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResourceVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'resource_type',
                    models.CharField(
                        choices=[('panel', '报表'), ('tool', '工具')], db_index=True, max_length=32, verbose_name='资源类型'
                    ),
                ),
                ('resource_id', models.CharField(db_index=True, max_length=64, verbose_name='资源ID')),
                (
                    'visibility_type',
                    models.CharField(
                        choices=[
                            ('all_visible', '全部可见'),
                            ('all_scenes', '全部场景'),
                            ('specific_scenes', '指定场景'),
                            ('specific_systems', '指定系统'),
                        ],
                        max_length=32,
                        verbose_name='可见范围类型',
                    ),
                ),
                ('scene_ids', models.JSONField(default=list, verbose_name='可见场景ID列表')),
                ('system_ids', models.JSONField(default=list, verbose_name='可见系统ID列表')),
            ],
            options={
                'verbose_name': '资源可见范围',
                'verbose_name_plural': '资源可见范围',
                'unique_together': {('resource_type', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='SceneSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('system_id', models.CharField(db_index=True, max_length=64, verbose_name='系统ID')),
                ('is_all_systems', models.BooleanField(default=False, verbose_name='是否关联全部系统')),
                ('filter_rules', models.JSONField(default=list, verbose_name='数据过滤规则')),
                (
                    'scene',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='scene_systems', to='scene.scene'
                    ),
                ),
            ],
            options={
                'verbose_name': '场景-系统关联',
                'verbose_name_plural': '场景-系统关联',
                'unique_together': {('scene', 'system_id')},
            },
        ),
        migrations.CreateModel(
            name='SceneDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('table_id', models.CharField(db_index=True, max_length=128, verbose_name='数据表ID')),
                ('filter_rules', models.JSONField(default=list, verbose_name='数据过滤规则')),
                (
                    'scene',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='scene_tables', to='scene.scene'
                    ),
                ),
            ],
            options={
                'verbose_name': '场景-数据表关联',
                'verbose_name_plural': '场景-数据表关联',
                'unique_together': {('scene', 'table_id')},
            },
        ),
    ]
