# Generated by Django 4.2.26 on 2026-04-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneTool',
        ),
    ]
