# Generated by Django 4.2.26 on 2026-04-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_remove_scene_tool_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenePanel',
        ),
    ]
