# Generated by Django 4.2.26 on 2026-04-08 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_delete_scenepanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'resource_type',
                    models.CharField(
                        choices=[('panel', '报表'), ('tool', '工具')], db_index=True, max_length=32, verbose_name='资源类型'
                    ),
                ),
                ('resource_id', models.CharField(db_index=True, max_length=64, verbose_name='资源ID')),
                (
                    'binding_type',
                    models.CharField(
                        choices=[('scene_binding', '场景级绑定'), ('platform_binding', '平台级绑定')],
                        db_index=True,
                        max_length=32,
                        verbose_name='绑定类型',
                    ),
                ),
                (
                    'visibility_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('all_visible', '全部可见'),
                            ('all_scenes', '全部场景'),
                            ('specific_scenes', '指定场景'),
                            ('specific_systems', '指定系统'),
                        ],
                        default='all_visible',
                        help_text='仅 platform_binding 时有效',
                        max_length=32,
                        verbose_name='可见范围类型',
                    ),
                ),
            ],
            options={
                'verbose_name': '资源绑定关系',
                'verbose_name_plural': '资源绑定关系',
                'unique_together': {('resource_type', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='ResourceBindingScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('scene_id', models.IntegerField(db_index=True, verbose_name='场景ID')),
                (
                    'binding',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='binding_scenes',
                        to='scene.resourcebinding',
                    ),
                ),
            ],
            options={
                'verbose_name': '资源绑定-场景关联',
                'verbose_name_plural': '资源绑定-场景关联',
                'unique_together': {('binding', 'scene_id')},
            },
        ),
        migrations.CreateModel(
            name='ResourceBindingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('system_id', models.CharField(db_index=True, max_length=64, verbose_name='系统ID')),
                (
                    'binding',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='binding_systems',
                        to='scene.resourcebinding',
                    ),
                ),
            ],
            options={
                'verbose_name': '资源绑定-系统关联',
                'verbose_name_plural': '资源绑定-系统关联',
                'unique_together': {('binding', 'system_id')},
            },
        ),
        migrations.DeleteModel(
            name='ResourceVisibility',
        ),
    ]
