# Generated by Django 4.2.26 on 2026-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_backfill_system_default_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebinding',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('panel', '报表'),
                    ('tool', '工具'),
                    ('strategy', '策略'),
                    ('link_table', '联表'),
                    ('process_application', '处理套餐'),
                    ('risk_rule', '处理规则'),
                    ('notice_group', '通知组'),
                    ('risk', '风险'),
                ],
                db_index=True,
                max_length=32,
                verbose_name='资源类型',
            ),
        ),
        migrations.AlterField(
            model_name='resourcebinding',
            name='visibility_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('all_visible', '全部可见'),
                    ('all_scenes', '全部场景'),
                    ('all_systems', '全系统'),
                    ('specific_scenes', '指定场景'),
                    ('specific_systems', '指定系统'),
                ],
                default='specific_scenes',
                help_text='仅 platform_binding 时有效',
                max_length=32,
                verbose_name='可见范围类型',
            ),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='场景名称'),
        ),
    ]
