# Generated by Django 4.2.26 on 2026-04-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_alter_resourcebinding_resource_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='iam_manager_group_id',
            field=models.BigIntegerField(blank=True, help_text='IAM 管理用户组 ID', null=True, verbose_name='管理用户组ID'),
        ),
        migrations.AddField(
            model_name='scene',
            name='iam_viewer_group_id',
            field=models.BigIntegerField(blank=True, help_text='IAM 使用用户组 ID', null=True, verbose_name='使用用户组ID'),
        ),
    ]
