# Generated by Django 4.2.26 on 2026-05-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0009_backfill_scene_iam_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='users',
        ),
    ]
