# Generated by Django 4.2.26 on 2026-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0010_remove_scene_managers_remove_scene_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='场景名称'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('name', 'is_deleted')},
        ),
    ]
