# Generated by Django 4.2.26 on 2026-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0011_scene_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='managers',
            field=models.JSONField(default=list, verbose_name='场景管理员列表'),
        ),
        migrations.AddField(
            model_name='scene',
            name='users',
            field=models.JSONField(default=list, verbose_name='场景使用者列表'),
        ),
    ]
