# Generated by Django 4.2.26 on 2026-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0012_scene_managers_scene_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebinding',
            name='visibility_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('all_visible', '全部可见'),
                    ('all_scenes', '全部场景'),
                    ('all_systems', '全系统'),
                    ('specific_scenes', '指定场景'),
                    ('specific_systems', '指定系统'),
                    ('scenes_and_systems', '场景和系统'),
                ],
                default='specific_scenes',
                help_text='仅 platform_binding 时有效',
                max_length=32,
                verbose_name='可见范围类型',
            ),
        ),
    ]
