# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0013_alter_resourcebinding_visibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
