# Generated by Django 3.2.12 on 2023-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature", "0002_alter_featuretoggle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretoggle",
            name="status",
            field=models.CharField(
                choices=[("deny", "已关闭"), ("stag", "测试环境"), ("prod", "正式环境"), ("available", "已启用")],
                default="deny",
                max_length=32,
                verbose_name="特性开关status",
            ),
        ),
    ]
