# Generated by Django 4.2.26 on 2026-08-13 09:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部 ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('PROCESSING', '处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')],
                        db_index=True,
                        default='PROCESSING',
                        max_length=32,
                        verbose_name='执行状态',
                    ),
                ),
                (
                    'task_id',
                    models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='任务 ID'),
                ),
                ('input_data', models.JSONField(default=dict, verbose_name='输入快照')),
                ('context_data', models.JSONField(default=dict, verbose_name='上下文快照')),
                ('output_data', models.JSONField(blank=True, default=None, null=True, verbose_name='输出快照')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='脱敏错误信息')),
                (
                    'attachment_type',
                    models.CharField(
                        choices=[
                            ('FIELD_STATISTICS', '字段统计'),
                            ('AI_STATISTICS', 'AI 统计'),
                            ('AI_ANALYSIS', 'AI 分析'),
                        ],
                        max_length=32,
                        verbose_name='附件类型',
                    ),
                ),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                (
                    'content_updated_at',
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='内容更新时间'),
                ),
                ('is_stream', models.BooleanField(default=False, verbose_name='是否流式执行')),
                ('stream_config', models.JSONField(default=dict, verbose_name='流式配置')),
                ('stream_archive', models.JSONField(blank=True, default=list, verbose_name='流式事件归档')),
            ],
            options={
                'verbose_name': 'AI 助手附件',
                'verbose_name_plural': 'AI 助手附件',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部 ID')),
                ('title', models.CharField(default='新对话', max_length=255, verbose_name='会话标题')),
            ],
            options={
                'verbose_name': 'AI 助手会话',
                'verbose_name_plural': 'AI 助手会话',
            },
        ),
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部 ID')),
                ('name', models.CharField(max_length=64, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': 'AI 助手会话分组',
                'verbose_name_plural': 'AI 助手会话分组',
            },
        ),
        migrations.CreateModel(
            name='ConversationSidebarNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'node_type',
                    models.CharField(
                        choices=[('GROUP', '分组'), ('CONVERSATION', '会话')], max_length=32, verbose_name='节点类型'
                    ),
                ),
                ('position', models.PositiveBigIntegerField(default=0, verbose_name='排序位置')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
            ],
            options={
                'verbose_name': 'AI 助手侧栏节点',
                'verbose_name_plural': 'AI 助手侧栏节点',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部 ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('PROCESSING', '处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')],
                        db_index=True,
                        default='PROCESSING',
                        max_length=32,
                        verbose_name='执行状态',
                    ),
                ),
                (
                    'task_id',
                    models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='任务 ID'),
                ),
                ('input_data', models.JSONField(default=dict, verbose_name='输入快照')),
                ('context_data', models.JSONField(default=dict, verbose_name='上下文快照')),
                ('output_data', models.JSONField(blank=True, default=None, null=True, verbose_name='输出快照')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='脱敏错误信息')),
                (
                    'message_type',
                    models.CharField(
                        choices=[
                            ('SYSTEM_SELECTION', '系统选择'),
                            ('NATURAL_LANGUAGE_SEARCH', '自然语言检索'),
                            ('LOG_SEARCH', '日志检索'),
                        ],
                        max_length=32,
                        verbose_name='消息类型',
                    ),
                ),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='ai_assistant.conversation',
                        verbose_name='所属会话',
                    ),
                ),
                (
                    'parent_message',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='child_messages',
                        to='ai_assistant.message',
                        verbose_name='父消息',
                    ),
                ),
            ],
            options={
                'verbose_name': 'AI 助手消息',
                'verbose_name_plural': 'AI 助手消息',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部 ID')),
                (
                    'source_type',
                    models.CharField(
                        choices=[('MESSAGE', '消息'), ('ATTACHMENT', '附件')], max_length=32, verbose_name='来源类型'
                    ),
                ),
                ('source_id', models.PositiveBigIntegerField(verbose_name='来源 ID')),
                (
                    'feedback_type',
                    models.CharField(choices=[('LIKE', '赞'), ('DISLIKE', '踩')], max_length=16, verbose_name='反馈类型'),
                ),
                ('comment', models.TextField(blank=True, default='', verbose_name='反馈说明')),
            ],
            options={
                'verbose_name': 'AI 助手反馈',
                'verbose_name_plural': 'AI 助手反馈',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='ai_feedback_source_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(
                fields=('created_by', 'source_type', 'source_id'), name='ai_feedback_user_source_uniq'
            ),
        ),
        migrations.AddField(
            model_name='conversationsidebarnode',
            name='conversation',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sidebar_node',
                to='ai_assistant.conversation',
                verbose_name='会话',
            ),
        ),
        migrations.AddField(
            model_name='conversationsidebarnode',
            name='group',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sidebar_node',
                to='ai_assistant.conversationgroup',
                verbose_name='分组',
            ),
        ),
        migrations.AddField(
            model_name='conversationsidebarnode',
            name='parent_node',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='ai_assistant.conversationsidebarnode',
                verbose_name='父节点',
            ),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by', 'is_deleted', 'updated_at', 'id'], name='ai_conv_owner_list_idx'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='source_message',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attachments',
                to='ai_assistant.message',
                verbose_name='来源消息',
            ),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='ai_msg_conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message', 'message_type', 'id'], name='ai_msg_parent_type_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'task_id'], name='ai_msg_task_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'updated_at', 'id'], name='ai_msg_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsidebarnode',
            index=models.Index(
                fields=['created_by', 'parent_node', 'position', 'id'], name='ai_node_container_pos_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='conversationsidebarnode',
            index=models.Index(fields=['created_by', 'pinned_at', 'id'], name='ai_node_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_message', 'id'], name='ai_att_source_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['status', 'task_id'], name='ai_att_task_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['status', 'updated_at', 'id'], name='ai_att_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(
                fields=['created_by', 'attachment_type', 'status', 'content_updated_at', 'id'],
                name='ai_att_owner_type_idx',
            ),
        ),
    ]
