# Generated by Django 4.2.26 on 2026-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='会话标题'),
        ),
    ]
