# Generated by Django 4.2.26 on 2026-08-24 13:22

from django.db import migrations, models


def backfill_execution_timestamps(apps, schema_editor):
    """用既有审计时间补齐存量对象，不在迁移期间改变任何执行状态。"""

    for model_name in ("Message", "Attachment"):
        model = apps.get_model("ai_assistant", model_name)
        model.objects.filter(status="PROCESSING").update(
            queued_at=models.F("created_at"),
            last_activity_at=models.F("updated_at"),
        )
        model.objects.exclude(status="PROCESSING").update(
            last_activity_at=models.F("updated_at"),
            finished_at=models.F("updated_at"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_conversation_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='ai_att_status_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='ai_msg_status_time_idx',
        ),
        migrations.AddField(
            model_name='attachment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近活动时间'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='排队时间'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近活动时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='排队时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.RunPython(backfill_execution_timestamps, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['status', 'last_activity_at', 'id'], name='ai_att_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'last_activity_at', 'id'], name='ai_msg_status_time_idx'),
        ),
    ]
