# Generated by Django 4.2.30 on 2026-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_conversation_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_by', 'message_type', 'id'], name='ai_msg_owner_type_idx'),
        ),
    ]
