# Generated by Django 4.2.30 on 2026-08-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_execution_timestamps'),
        ('ai_assistant', '0003_message_ai_msg_owner_type_idx'),
    ]

    operations = [
    ]
