# Generated by Django 4.2.30 on 2026-08-28 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_merge_20260826_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者')),
                ('selected_fields', models.JSONField(default=list, verbose_name='已选字段')),
            ],
            options={
                'verbose_name': 'AI 助手展示字段偏好',
                'verbose_name_plural': 'AI 助手展示字段偏好',
            },
        ),
        migrations.AddConstraint(
            model_name='usercolumnpreference',
            constraint=models.UniqueConstraint(fields=('created_by',), name='ai_column_pref_user_uniq'),
        ),
    ]
