# Generated by Django 4.2.30 on 2026-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_user_column_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='卡片可见性'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('SYSTEM_SELECTION', '系统选择'), ('USER_INTENT', '用户意图识别'), ('NATURAL_LANGUAGE_SEARCH', '自然语言检索'), ('LOG_SEARCH', '日志检索')], max_length=32, verbose_name='消息类型'),
        ),
    ]
