# Generated by Django 4.2.26 on 2026-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_message_visible_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(
                choices=[('SYSTEM_SELECTION', '系统选择'), ('USER_INTENT', '用户意图识别'), ('LOG_SEARCH', '日志检索')],
                max_length=32,
                verbose_name='消息类型',
            ),
        ),
    ]
