# Generated by Django 4.2.30 on 2026-09-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_init_log_analysis_prompt'),
        ('ai_assistant', '0006_message_visible_alter_message_message_type'),
    ]

    operations = [
    ]
