# Generated by Django 4.2.26 on 2026-09-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_merge_20260911_1900'),
        ('ai_assistant', '0007_remove_natural_language_search_message_type'),
    ]

    operations = []
