# Generated by Django 4.2.26 on 2026-09-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_conversation_scope'),
        ('ai_assistant', '0008_merge_20260924_1633'),
    ]

    operations = []
