# Generated by Django 3.2.18 on 2023-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="notice_groups",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Notice Groups"),
        ),
    ]
