# Generated by Django 3.2.18 on 2023-07-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_v2", "0002_strategy_notice_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="status_msg",
            field=models.TextField(blank=True, null=True, verbose_name="Status Message"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="configs",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Configs"),
        ),
    ]
