# Generated by Django 3.2.23 on 2024-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_v2", "0004_auto_20240118_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="event_basic_field_configs",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Event field Configs"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="event_data_field_configs",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Event Data Configs"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="event_evidence_field_configs",
            field=models.JSONField(default=dict, null=True, verbose_name="Event Evidence Configs"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="processor_groups",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Processor"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="risk_guidance",
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Risk Guidance"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="risk_hazard",
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Risk Hazard"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="risk_level",
            field=models.CharField(
                choices=[("HIGH", "高"), ("MIDDLE", "中"), ("LOW", "低")],
                default=None,
                max_length=16,
                null=True,
                verbose_name="Risk Level",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="risk_title",
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Risk Title"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="backend_data",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Backend Data"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("failed", "Failed"),
                    ("start_failed", "Start Failed"),
                    ("update_failed", "Update Failed"),
                    ("stop_failed", "Stop Failed"),
                    ("delete_failed", "Delete Failed"),
                    ("starting", "Starting"),
                    ("updating", "Updating"),
                    ("stopping", "Stopping"),
                    ("running", "Running"),
                ],
                default="starting",
                max_length=64,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="strategytag",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="strategytag",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
    ]
