# Generated by Django 3.2.23 on 2024-08-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_v2", "0006_auto_20240806_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="event_basic_field_configs",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Event field Configs"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="event_data_field_configs",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Event Data Configs"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="event_evidence_field_configs",
            field=models.JSONField(default=list, null=True, verbose_name="Event Evidence Configs"),
        ),
    ]
