# Generated by Django 3.2.23 on 2024-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_v2", "0007_auto_20240807_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="event_basic_field_configs",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Event Field Configs"),
        ),
    ]
