# Generated by Django 3.2.23 on 2025-01-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0009_auto_20241219_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='sql',
            field=models.TextField(blank=True, null=True, verbose_name='Rule Audit SQL'),
        ),
    ]
