# Generated by Django 3.2.23 on 2025-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0011_auto_20250114_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktable',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Link Table Name'),
        ),
    ]
