# Generated by Django 4.2.19 on 2025-06-11 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0013_auto_20250307_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('tool_uid', models.CharField(db_index=True, max_length=64, verbose_name='工具UID')),
                ('tool_version', models.IntegerField(db_index=True, verbose_name='工具版本')),
                ('field_name', models.CharField(db_index=True, max_length=64, verbose_name='字段名')),
                (
                    'field_source',
                    models.CharField(
                        choices=[('basic', '基本字段'), ('data', '数据字段'), ('evidence', '证据字段')],
                        max_length=16,
                        verbose_name='字段来源',
                    ),
                ),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tools',
                        to='strategy_v2.strategy',
                        verbose_name='Strategy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Strategy Tool',
                'verbose_name_plural': 'Strategy Tool',
                'ordering': ['-id'],
                'unique_together': {('strategy', 'field_source', 'field_name', 'tool_uid')},
            },
        ),
    ]
