# Generated by Django 4.2.23 on 2025-08-05 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0014_strategytool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytag',
            name='strategy',
            field=models.ForeignKey(
                db_column='strategy_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='strategy_v2.strategy',
                verbose_name='Strategy',
            ),
        ),
        migrations.AlterField(
            model_name='strategytag',
            name='tag',
            field=models.ForeignKey(
                db_column='tag_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='strategy_tags',
                to='meta.tag',
                verbose_name='Tag',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='strategytag',
            unique_together={('strategy', 'tag')},
        ),
        migrations.AlterField(
            model_name='strategytag',
            name='strategy',
            field=models.ForeignKey(
                db_column='strategy_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='strategy_v2.strategy',
                verbose_name='Strategy',
            ),
        ),
        migrations.AlterField(
            model_name='strategytag',
            name='tag',
            field=models.ForeignKey(
                db_column='tag_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='strategy_tags',
                to='meta.tag',
                verbose_name='Tag',
            ),
        ),
    ]
