# Generated by Django 4.2.23 on 2025-09-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0016_strategy_is_formal'),
        ('strategy_v2', '0016_strategy_risk_field_config'),
    ]

    operations = []
