# Generated by Django 4.2.25 on 2025-10-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0018_storage_node_ids_map'),
        ('strategy_v2', '0018_update_drill_config_to_list'),
    ]

    operations = []
