# Generated by Django 4.2.25 on 2025-11-05 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0018_storage_node_ids_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTagSyncTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('original_id', models.BigIntegerField(unique=True, verbose_name='Strategy Tag ID')),
                ('strategy_id', models.BigIntegerField(default=0, verbose_name='Strategy ID')),
                ('tag_id', models.BigIntegerField(default=0, verbose_name='Tag ID')),
            ],
            options={
                'verbose_name': 'Strategy Tag Tombstone',
                'verbose_name_plural': 'Strategy Tag Tombstone',
                'ordering': ['-id'],
            },
        ),
    ]
