# Generated by Django 4.2.26 on 2025-11-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0018_update_drill_config_to_list'),
        ('strategy_v2', '0019_strategytagsynctrash'),
    ]

    operations = []
