# Generated by Django 4.2.25 on 2025-11-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0019_merge_20251023_1441'),
        ('strategy_v2', '0019_strategytagsynctrash'),
    ]

    operations = []
