# Generated by Django 4.2.26 on 2025-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0020_merge_20251110_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='source',
            field=models.CharField(
                choices=[('user', '用户创建'), ('system', '系统创建')],
                db_index=True,
                default='user',
                max_length=16,
                verbose_name='Source',
            ),
        ),
    ]
