# Generated by Django 4.2.26 on 2026-01-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0021_strategy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='report_config',
            field=models.JSONField(
                blank=True, default=dict, help_text='报告模板配置（template + ai_variables）', verbose_name='报告配置'
            ),
        ),
        migrations.AddField(
            model_name='strategy',
            name='report_enabled',
            field=models.BooleanField(default=False, help_text='启用后，风险单会自动生成事件调查报告', verbose_name='是否启用报告'),
        ),
    ]
