# Generated by Django 4.2.26 on 2026-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0022_add_render_task_risk_report_auto_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='report_auto_render',
            field=models.BooleanField(default=True, help_text='启用后，新事件触发时会自动渲染报告', verbose_name='是否启用自动渲染报告'),
        ),
    ]
