# Generated by Django 4.2.30 on 2026-08-17 06:32
# 所有 DDL 操作加存在性守卫：表/列/索引已存在时跳过，仅保证结构最终一致，不触碰数据。

import django.utils.timezone
from django.db import migrations, models


def _default_strategy_rule_conditions() -> dict:
    return {"where": None, "having": None}


def _default_dispatch_rule_conditions() -> dict:
    return {}


def table_exists(schema_editor, table: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s",
            [table],
        )
        return cursor.fetchone()[0] > 0


def column_exists(schema_editor, table: str, column: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            [table, column],
        )
        return cursor.fetchone()[0] > 0


def index_exists(schema_editor, table: str, index_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s",
            [table, index_name],
        )
        return cursor.fetchone()[0] > 0


class SafeCreateModel(migrations.CreateModel):
    """表已存在时跳过建表（列结构由本迁移其余操作/历史版本保证）"""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if table_exists(schema_editor, model._meta.db_table):
            print(f"[SafeCreateModel] table exists, skip => {model._meta.db_table}")
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAddField(migrations.AddField):
    """列已存在时跳过（兼容历史版本迁移已部分执行的环境）"""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table = model._meta.db_table
        if column_exists(schema_editor, table, model._meta.get_field(self.name).column):
            print(f"[SafeAddField] column exists, skip => {table}.{self.name}")
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAddIndex(migrations.AddIndex):
    """同名索引已存在时跳过"""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if index_exists(schema_editor, model._meta.db_table, self.index.name):
            print(f"[SafeAddIndex] index exists, skip => {model._meta.db_table}.{self.index.name}")
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0025_remove_scene_id'),
        ('scene', '0013_alter_resourcebinding_visibility_type'),
    ]

    operations = [
        SafeAddField(
            model_name='strategy',
            name='dispatch_rule_order',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='分派规则优先级列表 [dispatch_rule_id, ...]，仅全局策略有',
                verbose_name='Dispatch Rule Order',
            ),
        ),
        SafeAddField(
            model_name='strategy',
            name='rule_order',
            field=models.JSONField(
                blank=True, default=list, help_text='发现规则匹配优先级列表 [rule_id, ...]', verbose_name='Rule Order'
            ),
        ),
        SafeCreateModel(
            name='StrategyRule',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rule ID')),
                ('rule_name', models.CharField(help_text='规则名称', max_length=64, verbose_name='Rule Name')),
                (
                    'conditions',
                    models.JSONField(
                        blank=True,
                        default=_default_strategy_rule_conditions,
                        help_text='发现规则命中条件，结构：{"where": {...}, "having": {...}}',
                        verbose_name='Conditions',
                    ),
                ),
                (
                    'risk_title',
                    models.CharField(
                        blank=True, help_text='风险标题模板', max_length=255, null=True, verbose_name='Risk Title'
                    ),
                ),
                (
                    'risk_level',
                    models.CharField(blank=True, help_text='风险等级', max_length=16, null=True, verbose_name='Risk Level'),
                ),
                (
                    'risk_hazard',
                    models.TextField(blank=True, help_text='风险危害描述', null=True, verbose_name='Risk Hazard'),
                ),
                (
                    'risk_guidance',
                    models.TextField(blank=True, help_text='处理指引', null=True, verbose_name='Risk Guidance'),
                ),
                (
                    'processor',
                    models.JSONField(
                        blank=True, default=list, help_text='处理人通知组 ID 列表（场景策略使用）', verbose_name='Processor'
                    ),
                ),
                (
                    'follower',
                    models.JSONField(
                        blank=True, default=list, help_text='关注人通知组 ID 列表（场景策略使用）', verbose_name='Follower'
                    ),
                ),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='rules',
                        to='strategy_v2.strategy',
                        verbose_name='Strategy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Strategy Rule',
                'verbose_name_plural': 'Strategy Rule',
                'ordering': ['strategy', 'rule_id'],
            },
        ),
        SafeAddIndex(
            model_name='strategyrule',
            index=models.Index(fields=['strategy', 'is_deleted'], name='idx_srule_strategy_isdel'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyrule',
            unique_together={('strategy', 'rule_name')},
        ),
        SafeCreateModel(
            name='DispatchRule',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rule ID')),
                ('rule_name', models.CharField(help_text='规则名称', max_length=64, verbose_name='Rule Name')),
                (
                    'conditions',
                    models.JSONField(
                        blank=True,
                        default=_default_dispatch_rule_conditions,
                        help_text='匹配条件树（WhereCondition 结构），空 dict = 默认兜底规则',
                        null=True,
                        verbose_name='Conditions',
                    ),
                ),
                (
                    'processor',
                    models.JSONField(blank=True, default=list, help_text='处理人通知组 ID 列表', verbose_name='Processor'),
                ),
                (
                    'follower',
                    models.JSONField(blank=True, default=list, help_text='关注人通知组 ID 列表', verbose_name='Follower'),
                ),
                (
                    'confirmer',
                    models.JSONField(blank=True, default=list, help_text='确认人通知组 ID 列表', verbose_name='Confirmer'),
                ),
                (
                    'dispatch_mode',
                    models.CharField(
                        choices=[('direct', '直接分派'), ('after_confirm', '确认后分派')],
                        default='direct',
                        help_text='分派方式：direct=直接分派，after_confirm=确认后分派',
                        max_length=32,
                        verbose_name='Dispatch Mode',
                    ),
                ),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认兜底规则', verbose_name='Is Default')),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dispatch_rules',
                        to='strategy_v2.strategy',
                        verbose_name='Strategy',
                    ),
                ),
                (
                    'target_scene',
                    models.ForeignKey(
                        db_column='target_scene_id',
                        db_constraint=False,
                        help_text='目标场景',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dispatch_rules',
                        to='scene.scene',
                        verbose_name='Target Scene',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dispatch Rule',
                'verbose_name_plural': 'Dispatch Rule',
                'ordering': ['strategy', 'rule_id'],
            },
        ),
        SafeAddIndex(
            model_name='dispatchrule',
            index=models.Index(fields=['strategy', 'is_deleted'], name='idx_drule_strategy_isdel'),
        ),
        migrations.AlterUniqueTogether(
            name='dispatchrule',
            unique_together={('strategy', 'rule_name')},
        ),
    ]
