# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0025_remove_scene_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
