# Generated by Django 4.2.30 on 2026-08-17 06:32

import django.utils.timezone
from django.db import migrations, models


def _default_strategy_rule_conditions() -> dict:
    return {"where": None, "having": None}


def _default_dispatch_rule_conditions() -> dict:
    return {}


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0025_remove_scene_id'),
        ('scene', '0013_alter_resourcebinding_visibility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='dispatch_rule_order',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='分派规则优先级列表 [dispatch_rule_id, ...]，仅全局策略有',
                verbose_name='Dispatch Rule Order',
            ),
        ),
        migrations.AddField(
            model_name='strategy',
            name='rule_order',
            field=models.JSONField(
                blank=True, default=list, help_text='发现规则匹配优先级列表 [rule_id, ...]', verbose_name='Rule Order'
            ),
        ),
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rule ID')),
                ('rule_name', models.CharField(help_text='规则名称', max_length=64, verbose_name='Rule Name')),
                (
                    'conditions',
                    models.JSONField(
                        blank=True,
                        default=_default_strategy_rule_conditions,
                        help_text='发现规则命中条件，结构：{"where": {...}, "having": {...}}',
                        verbose_name='Conditions',
                    ),
                ),
                (
                    'risk_title',
                    models.CharField(
                        blank=True, help_text='风险标题模板', max_length=255, null=True, verbose_name='Risk Title'
                    ),
                ),
                (
                    'risk_level',
                    models.CharField(blank=True, help_text='风险等级', max_length=16, null=True, verbose_name='Risk Level'),
                ),
                (
                    'risk_hazard',
                    models.TextField(blank=True, help_text='风险危害描述', null=True, verbose_name='Risk Hazard'),
                ),
                (
                    'risk_guidance',
                    models.TextField(blank=True, help_text='处理指引', null=True, verbose_name='Risk Guidance'),
                ),
                (
                    'processor',
                    models.JSONField(
                        blank=True, default=list, help_text='处理人通知组 ID 列表（场景策略使用）', verbose_name='Processor'
                    ),
                ),
                (
                    'follower',
                    models.JSONField(
                        blank=True, default=list, help_text='关注人通知组 ID 列表（场景策略使用）', verbose_name='Follower'
                    ),
                ),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='rules',
                        to='strategy_v2.strategy',
                        verbose_name='Strategy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Strategy Rule',
                'verbose_name_plural': 'Strategy Rule',
                'ordering': ['strategy', 'rule_id'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyrule',
            index=models.Index(fields=['strategy', 'is_deleted'], name='idx_srule_strategy_isdel'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyrule',
            unique_together={('strategy', 'rule_name')},
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rule ID')),
                ('rule_name', models.CharField(help_text='规则名称', max_length=64, verbose_name='Rule Name')),
                (
                    'conditions',
                    models.JSONField(
                        blank=True,
                        default=_default_dispatch_rule_conditions,
                        help_text='匹配条件树（WhereCondition 结构），空 dict = 默认兜底规则',
                        null=True,
                        verbose_name='Conditions',
                    ),
                ),
                (
                    'processor',
                    models.JSONField(blank=True, default=list, help_text='处理人通知组 ID 列表', verbose_name='Processor'),
                ),
                (
                    'follower',
                    models.JSONField(blank=True, default=list, help_text='关注人通知组 ID 列表', verbose_name='Follower'),
                ),
                (
                    'confirmer',
                    models.JSONField(blank=True, default=list, help_text='确认人通知组 ID 列表', verbose_name='Confirmer'),
                ),
                (
                    'dispatch_mode',
                    models.CharField(
                        choices=[('direct', '直接分派'), ('after_confirm', '确认后分派')],
                        default='direct',
                        help_text='分派方式：direct=直接分派，after_confirm=确认后分派',
                        max_length=32,
                        verbose_name='Dispatch Mode',
                    ),
                ),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认兜底规则', verbose_name='Is Default')),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dispatch_rules',
                        to='strategy_v2.strategy',
                        verbose_name='Strategy',
                    ),
                ),
                (
                    'target_scene',
                    models.ForeignKey(
                        db_column='target_scene_id',
                        db_constraint=False,
                        help_text='目标场景',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dispatch_rules',
                        to='scene.scene',
                        verbose_name='Target Scene',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dispatch Rule',
                'verbose_name_plural': 'Dispatch Rule',
                'ordering': ['strategy', 'rule_id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchrule',
            index=models.Index(fields=['strategy', 'is_deleted'], name='idx_drule_strategy_isdel'),
        ),
        migrations.AlterUniqueTogether(
            name='dispatchrule',
            unique_together={('strategy', 'rule_name')},
        ),
    ]
