# Generated by Django 3.2.12 on 2023-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzeconfig",
            name="analyze_type",
            field=models.CharField(choices=[("normal", "常规"), ("aiops", "Aiops")], max_length=64, verbose_name="分析类型"),
        ),
    ]
