# Generated by Django 3.2.18 on 2023-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0004_control_controlversion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyzeConfig",
        ),
        migrations.DeleteModel(
            name="AnalyzeFieldConfig",
        ),
        migrations.AddField(
            model_name="control",
            name="priority_index",
            field=models.IntegerField(default=0, verbose_name="Priority Index"),
        ),
        migrations.AlterField(
            model_name="control",
            name="control_type_id",
            field=models.CharField(
                choices=[("BKM", "BK Monitor"), ("AIOps", "BK Base AIOps")],
                max_length=64,
                verbose_name="Control Type ID",
            ),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="extra_config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Extra Config"),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="input_config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Input Config"),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="output_config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Output Config"),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="variable_config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Variable Config"),
        ),
    ]
