# Generated by Django 3.2.18 on 2023-06-01 10:47

from django.db import migrations, transaction
from django.utils.translation import gettext

from services.web.analyze.constants import ControlTypeChoices
from services.web.analyze.models import Control, ControlVersion


@transaction.atomic()
def create_default_control(*args, **kwargs):
    if Control.objects.all().count():
        return
    control = Control.objects.create(control_name=gettext("操作行为审计"), control_type_id=ControlTypeChoices.BKM)
    ControlVersion.objects.create(control_id=control.control_id, control_version=1)


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0006_alter_control_options"),
    ]

    operations = [
        migrations.RunPython(create_default_control),
    ]
