# Generated by Django 3.2.23 on 2024-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0007_init_default_control"),
    ]

    operations = [
        migrations.AlterField(
            model_name="control",
            name="control_type_id",
            field=models.CharField(
                choices=[("BKM", "Operate Audit"), ("AIOps", "BK Base AIOps")],
                max_length=64,
                verbose_name="Control Type ID",
            ),
        ),
        migrations.AlterField(
            model_name="control",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="control",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="controlversion",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
    ]
