# Generated by Django 4.2.19 on 2025-04-28 08:33

import blueapps.utils.db
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LogExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('namespace', models.CharField(db_index=True, max_length=32, verbose_name='namespace')),
                ('repeat_times', models.IntegerField(default=0, verbose_name='任务执行次数')),
                (
                    'status',
                    models.CharField(
                        choices=[('READY', '就绪'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILURE', '失败')],
                        max_length=32,
                        verbose_name='任务状态',
                    ),
                ),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='任务执行结果')),
                ('task_start_time', models.DateTimeField(default=None, null=True, verbose_name='任务执行开始时间')),
                ('task_end_time', models.DateTimeField(default=None, null=True, verbose_name='任务执行结束时间')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='检索参数')),
                ('export_config', models.JSONField(blank=True, default=dict, verbose_name='导出配置')),
                ('total', models.IntegerField(default=0, verbose_name='总条数')),
                ('search_params_url', models.TextField(blank=True, null=True, verbose_name='查询参数URL')),
                ('current_records', models.IntegerField(default=0, verbose_name='当前记录数')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='任务名称')),
            ],
            options={
                'verbose_name': '日志导出任务',
                'verbose_name_plural': '日志导出任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportFieldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('raw_name', models.CharField(db_index=True, max_length=64, verbose_name='字段名称')),
                (
                    'keys',
                    blueapps.utils.db.MultiStrSplitCharField(
                        blank=True, db_index=True, default='', max_length=512, verbose_name='字段键'
                    ),
                ),
                ('display_name', models.CharField(db_index=True, max_length=255, verbose_name='展示名称')),
            ],
            options={
                'verbose_name': '字段展示配置',
                'verbose_name_plural': '字段展示配置',
            },
        ),
    ]
