# Generated by Django 4.2.19 on 2025-05-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexporttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('READY', '就绪'),
                    ('RUNNING', '执行中'),
                    ('SUCCESS', '成功'),
                    ('FAILURE', '失败'),
                    ('EXPIRED', '已过期'),
                ],
                max_length=32,
                verbose_name='任务状态',
            ),
        ),
        migrations.CreateModel(
            name='TaskDownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('downloaded_by', models.CharField(db_index=True, max_length=64, verbose_name='下载用户')),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='download_records',
                        to='query.logexporttask',
                        verbose_name='关联任务',
                    ),
                ),
            ],
            options={
                'verbose_name': '任务下载记录',
                'verbose_name_plural': '任务下载记录',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
