# Generated by Django 4.2.19 on 2025-05-07 12:14

import blueapps.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexporttask',
            name='current_records',
            field=models.IntegerField(default=0, verbose_name='当前记录数'),
        ),
        migrations.AddField(
            model_name='logexporttask',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='任务名称'),
        ),
    ]
