# Generated by Django 4.2.19 on 2025-04-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritesearch',
            old_name='filters',
            new_name='conditions',
        ),
    ]
