# Generated by Django 4.2.19 on 2025-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_logexporttask_status_taskdownloadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexporttask',
            name='task_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='任务执行结束时间'),
        ),
        migrations.AlterField(
            model_name='logexporttask',
            name='task_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='任务执行开始时间'),
        ),
    ]
