# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_logexporttask_alert_sented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexporttask',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
