# Generated by Django 4.2.26 on 2026-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_logexporttask_alert_sented'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexporttask',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='来源 ID'),
        ),
        migrations.AddField(
            model_name='logexporttask',
            name='source_type',
            field=models.CharField(
                choices=[('WEB_LOG_SEARCH', 'Web 日志检索'), ('AI_ASSISTANT_MESSAGE', 'AI 助手日志检索消息')],
                default='WEB_LOG_SEARCH',
                max_length=32,
                verbose_name='来源类型',
            ),
        ),
        migrations.AddIndex(
            model_name='logexporttask',
            index=models.Index(fields=['source_type', 'source_id'], name='query_export_source_idx'),
        ),
    ]
