# definition.yaml 配置文件版本号，必填，固定值 1/2
spec_version: 2  # 如果之前接入过的，建议将 sepc_version改成 2，并将原先 stage:改成 stages: []

release:
  # 发布版本号；
  # 资源配置更新，需更新此版本号才会发布资源版本，此版本号和 sdk 版本号一致，错误设置会影响调用方使用
  version: "0.0.5"
  # 版本标题
  title: "0.0.5"
  # 版本描述
  comment: "升级 apigw 描述文件版本，新增风险事件订阅、审计后端服务接口"

# 定义网关基本信息，用于命令 `sync_apigw_config`
apigateway:
  description: "审计中心"
  # 网关的英文描述，蓝鲸官方网关需提供英文描述，以支持国际化
  description_en: "BK Audit"
  # 是否公开；公开，则用户可查看资源文档、申请资源权限；不公开，则网关对用户隐藏
  is_public: true
  # 标记网关为官方网关，网关名需以 `bk-` 开头，可选；非官方网关，可去除此配置
  api_type: 1
  # 网关维护人员，仅维护人员有管理网关的权限
  maintainers:
{% for admin in settings.SYSTEM_ADMIN %}
      - "{{ admin }}"
{% endfor %}

# 定义环境信息，用于命令 `sync_apigw_stage`
stages:
  - name: "stag"
    description: "预发布环境"
    # 环境的英文名，蓝鲸官方网关需提供，以支持国际化
    description_en: "preRelease"
    proxy_http:
      timeout: 60
      upstreams:
        loadbalance: "roundrobin"
        hosts:
          - host: "{{ settings.BKAUDIT_API_STAG_HOST }}"
            weight: 100
  - name: "prod"
    description: "生产环境"
    # 环境的英文名，蓝鲸官方网关需提供，以支持国际化
    description_en: "formalRelease"
    proxy_http:
      timeout: 60
      upstreams:
        loadbalance: "roundrobin"
        hosts:
          - host: "{{ settings.BKAUDIT_API_HOST }}"
            weight: 100

# 为网关添加关联应用，关联应用可以通过网关 bk-apigateway 的接口操作网关数据；每个网关最多可有 10 个关联应用；
# 用于命令 `add_related_apps`
related_apps:
  - "{{ settings.APP_CODE }}" ## 环境变量方式："{{ environ.BK_APP_CODE }}"

# 定义资源文档路径，用于命令 `sync_resource_docs_by_archive`；
# 资源文档的目录格式样例如下，en 为英文文档，zh 为中文文档，创建归档文件可使用指令 `tar czvf xxx.tgz en zh`：
# ./
# - en
#   - get_user.md
# - zh
#   - get_user.md
resource_docs:
  # 资源文档的归档文件，可为 tar.gz，zip 格式文件
  # 资源文档目录，basedir 与 archivefile 二者至少一个有效，若同时存在，则 archivefile 优先
  basedir: "{{ settings.BK_APIGW_RESOURCE_DOCS_BASE_DIR }}"