# Generated by Django 3.2.18 on 2023-11-08 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vision", "0001_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionPanel",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("priority_index", models.IntegerField(default=0, verbose_name="优先指数")),
            ],
            options={
                "verbose_name": "仪表盘",
                "verbose_name_plural": "仪表盘",
                "ordering": ["-priority_index", "name"],
            },
        ),
    ]
