# Generated by Django 4.2.19 on 2025-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_visionpanel_handler_visionpanel_vision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionpanel',
            name='scenario',
            field=models.CharField(default='default', max_length=255, verbose_name='场景'),
        ),
    ]
