# Generated by Django 3.2.23 on 2025-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0005_visionpanel_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionpanel',
            name='scenario',
            field=models.CharField(
                choices=[('default', '默认'), ('per_app', '按应用')], default='default', max_length=255, verbose_name='场景'
            ),
        ),
    ]
