# Generated by Django 4.2.19 on 2025-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_alter_visionpanel_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionpanel',
            name='scenario',
            field=models.CharField(
                choices=[('default', '默认'), ('per_app', '按应用'), ('tool', '工具')],
                default='default',
                max_length=255,
                verbose_name='场景',
            ),
        ),
    ]
