# Generated by Django 4.2.19 on 2025-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_alter_visionpanel_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionpanel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
