# Generated by Django 4.2.26 on 2026-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_alter_visionpanel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionpanel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='scene_id',
            field=models.IntegerField(
                blank=True, db_index=True, help_text='仅 scope_type=scene 时有值', null=True, verbose_name='所属场景ID'
            ),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='scope_type',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='platform=平台级, scene=场景级, 空=存量数据',
                max_length=32,
                verbose_name='归属级别',
            ),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='status',
            field=models.CharField(
                blank=True,
                default='',
                help_text='published=已上架, unpublished=未上架, 空=存量数据',
                max_length=32,
                verbose_name='上架状态',
            ),
        ),
    ]
