# Generated by Django 4.2.26 on 2026-03-30 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_alter_visionpanel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分组名称')),
                ('priority_index', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '报表分组',
                'verbose_name_plural': '报表分组',
                'ordering': ['-priority_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('config', models.JSONField(default=dict, verbose_name='偏好配置')),
            ],
            options={
                'verbose_name': '用户报表偏好',
                'verbose_name_plural': '用户报表偏好',
            },
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='visionpanel',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='panels',
                to='vision.reportgroup',
                verbose_name='所属分组',
            ),
        ),
    ]
