# Generated by Django 4.2.26 on 2026-04-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0009_visionpanel_category_visionpanel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionpanel',
            name='scene_id',
        ),
        migrations.RemoveField(
            model_name='visionpanel',
            name='scope_type',
        ),
    ]
