# Generated by Django 4.2.26 on 2026-03-31 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0010_init_report_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPanelFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='用户名')),
                (
                    'panel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='vision.visionpanel',
                        verbose_name='收藏的 Panel',
                    ),
                ),
            ],
            options={
                'verbose_name': '用户 Panel 收藏',
                'verbose_name_plural': '用户 Panel 收藏',
                'ordering': ['-created_at'],
                'unique_together': {('username', 'panel')},
            },
        ),
    ]
