# Generated by Django 4.2.26 on 2026-04-17 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_scene_iam_manager_group_id_scene_iam_viewer_group_id'),
        ('vision', '0010_resource_binding_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('config', models.JSONField(default=dict, verbose_name='偏好配置')),
            ],
            options={
                'verbose_name': '用户报表偏好',
                'verbose_name_plural': '用户报表偏好',
            },
        ),
        migrations.CreateModel(
            name='SceneReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='分组名称')),
                (
                    'group_type',
                    models.CharField(
                        choices=[('platform', '平台报表'), ('custom', '自定义分组')],
                        db_index=True,
                        default='custom',
                        max_length=32,
                        verbose_name='分组类型',
                    ),
                ),
                ('priority_index', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
                (
                    'scene',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='report_groups', to='scene.scene'
                    ),
                ),
            ],
            options={
                'verbose_name': '场景报表分组',
                'verbose_name_plural': '场景报表分组',
                'ordering': ['-priority_index', 'id'],
                'unique_together': {('scene', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserPanelFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='用户名')),
                (
                    'panel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='vision.visionpanel',
                        verbose_name='收藏报表',
                    ),
                ),
            ],
            options={
                'verbose_name': '用户报表收藏',
                'verbose_name_plural': '用户报表收藏',
                'ordering': ['-created_at'],
                'unique_together': {('username', 'panel')},
            },
        ),
        migrations.CreateModel(
            name='SceneReportGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('priority_index', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vision.scenereportgroup'
                    ),
                ),
                (
                    'panel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scene_group_items',
                        to='vision.visionpanel',
                    ),
                ),
            ],
            options={
                'verbose_name': '场景报表分组项',
                'verbose_name_plural': '场景报表分组项',
                'ordering': ['-priority_index', 'id'],
                'unique_together': {('group', 'panel')},
            },
        ),
        migrations.AlterField(
            model_name='visionpanel',
            name='status',
            field=models.CharField(
                choices=[('published', '已上架'), ('unpublished', '未上架')],
                default='unpublished',
                help_text='published=已上架, unpublished=未上架',
                max_length=32,
                verbose_name='上架状态',
            ),
        ),
    ]
