# Generated by Django 4.2.26 on 2026-04-22

from django.db import migrations


def forwards(apps, schema_editor):
    VisionPanel = apps.get_model("vision", "VisionPanel")
    VisionPanel.objects.filter(status="").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0011_reportuserpreference_scenereportgroup_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
