# Generated by Django 4.2.26 on 2026-04-22

from django.db import migrations

DEFAULT_SCENE_NAME = "system_default"
RESOURCE_TYPE_PANEL = "panel"
BINDING_TYPE_SCENE = "scene_binding"
LEGACY_SCENARIOS_TO_UNBIND = {"tool", "per_app"}


def _iter_legacy_scenes(Scene):
    """只处理历史默认场景，避免误删用户自定义场景绑定。"""
    return Scene._base_manager.filter(name=DEFAULT_SCENE_NAME).order_by("scene_id")


def _remove_non_default_panel_scene_bindings(
    VisionPanel,
    ResourceBinding,
    ResourceBindingScene,
    SceneReportGroupItem,
    legacy_scene,
):
    """清理挂在历史默认场景上的非 default 报表场景绑定。"""
    bindings = ResourceBinding._base_manager.filter(
        resource_type=RESOURCE_TYPE_PANEL,
        binding_type=BINDING_TYPE_SCENE,
        binding_scenes__scene_id=legacy_scene.scene_id,
        resource_id__in=VisionPanel._base_manager.filter(scenario__in=LEGACY_SCENARIOS_TO_UNBIND).values_list(
            "id", flat=True
        ),
    ).distinct()

    relation_count = 0
    deleted_binding_count = 0
    deleted_group_item_count = 0

    for binding in bindings:
        relation_count += ResourceBindingScene._base_manager.filter(
            binding_id=binding.id,
            scene_id=legacy_scene.scene_id,
        ).delete()[0]
        deleted_group_item_count += SceneReportGroupItem._base_manager.filter(
            panel_id=binding.resource_id,
            group__scene_id=legacy_scene.scene_id,
        ).delete()[0]
        if not ResourceBindingScene._base_manager.filter(binding_id=binding.id).exists():
            binding.delete()
            deleted_binding_count += 1

    print(
        "[0013] 清理历史非 default 报表场景绑定: "
        f"scene={legacy_scene.scene_id}, removed_relations={relation_count}, "
        f"deleted_bindings={deleted_binding_count}, deleted_group_items={deleted_group_item_count}"
    )


def forwards(apps, schema_editor):
    Scene = apps.get_model("scene", "Scene")
    ResourceBinding = apps.get_model("scene", "ResourceBinding")
    ResourceBindingScene = apps.get_model("scene", "ResourceBindingScene")
    VisionPanel = apps.get_model("vision", "VisionPanel")
    SceneReportGroupItem = apps.get_model("vision", "SceneReportGroupItem")

    print("[0013] 开始清理历史非 default 报表的默认场景绑定")
    for legacy_scene in _iter_legacy_scenes(Scene):
        _remove_non_default_panel_scene_bindings(
            VisionPanel,
            ResourceBinding,
            ResourceBindingScene,
            SceneReportGroupItem,
            legacy_scene,
        )
    print("[0013] 清理历史非 default 报表的默认场景绑定完成")


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0007_alter_resourcebinding_resource_type_and_more"),
        ("vision", "0012_backfill_visionpanel_status"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
