# Generated by Django 4.2.26 on 2026-04-22

from django.db import migrations

DEFAULT_SCENE_NAME = "system_default"
DEFAULT_SCENE_REPORT_GROUP_NAME = "默认分组"
DEFAULT_SCENE_REPORT_GROUP_PRIORITY = 0

RESOURCE_TYPE_PANEL = "panel"
SCENARIO_DEFAULT = "default"
BINDING_TYPE_SCENE = "scene_binding"
GROUP_TYPE_CUSTOM = "custom"


def _get_default_scene(Scene):
    return Scene._base_manager.filter(name=DEFAULT_SCENE_NAME).order_by("scene_id").first()


def _iter_legacy_scenes(Scene):
    """只处理历史默认场景。"""
    return Scene._base_manager.filter(name=DEFAULT_SCENE_NAME).order_by("scene_id")


def _ensure_default_group(SceneReportGroup, scene_id):
    """默认场景下必须存在默认分组，历史报表才能在分组视图中展示。"""
    group = (
        SceneReportGroup._base_manager.filter(scene_id=scene_id, name=DEFAULT_SCENE_REPORT_GROUP_NAME)
        .order_by("id")
        .first()
    )
    if group:
        if group.group_type != GROUP_TYPE_CUSTOM or group.priority_index != DEFAULT_SCENE_REPORT_GROUP_PRIORITY:
            group.group_type = GROUP_TYPE_CUSTOM
            group.priority_index = DEFAULT_SCENE_REPORT_GROUP_PRIORITY
            group.save(update_fields=["group_type", "priority_index"])
        return group, False

    return (
        SceneReportGroup._base_manager.create(
            scene_id=scene_id,
            name=DEFAULT_SCENE_REPORT_GROUP_NAME,
            group_type=GROUP_TYPE_CUSTOM,
            priority_index=DEFAULT_SCENE_REPORT_GROUP_PRIORITY,
        ),
        True,
    )


def _backfill_default_panel_group_items(
    VisionPanel,
    ResourceBinding,
    ResourceBindingScene,
    SceneReportGroupItem,
    default_group,
    legacy_scene,
):
    """给历史默认场景里的 default 报表补默认分组。"""
    bindings = ResourceBinding._base_manager.filter(
        resource_type=RESOURCE_TYPE_PANEL,
        binding_type=BINDING_TYPE_SCENE,
        binding_scenes__scene_id=legacy_scene.scene_id,
        resource_id__in=VisionPanel._base_manager.filter(scenario=SCENARIO_DEFAULT).values_list("id", flat=True),
    ).distinct()

    created_group_item_count = 0
    skipped_binding_count = 0

    for binding in bindings:
        scene_ids = list(
            ResourceBindingScene._base_manager.filter(binding_id=binding.id).values_list("scene_id", flat=True)
        )
        # 只处理“唯一场景归属就是历史默认场景”的 default 报表，避免覆盖用户已经调整过的归属。
        if set(scene_ids) != {legacy_scene.scene_id}:
            skipped_binding_count += 1
            continue

        _, created = SceneReportGroupItem._base_manager.get_or_create(
            group_id=default_group.id,
            panel_id=binding.resource_id,
            defaults={"priority_index": 0},
        )
        if created:
            created_group_item_count += 1

    print(
        "[0014] 回填默认场景报表分组: "
        f"legacy_scene={legacy_scene.scene_id}, created_group_items={created_group_item_count}, "
        f"skipped_bindings={skipped_binding_count}"
    )


def forwards(apps, schema_editor):
    Scene = apps.get_model("scene", "Scene")
    ResourceBinding = apps.get_model("scene", "ResourceBinding")
    ResourceBindingScene = apps.get_model("scene", "ResourceBindingScene")
    VisionPanel = apps.get_model("vision", "VisionPanel")
    SceneReportGroup = apps.get_model("vision", "SceneReportGroup")
    SceneReportGroupItem = apps.get_model("vision", "SceneReportGroupItem")

    default_scene = _get_default_scene(Scene)
    if not default_scene:
        print("[0014] 默认场景不存在，跳过历史 default 报表分组回填")
        return

    default_group, created = _ensure_default_group(SceneReportGroup, default_scene.scene_id)
    print("[0014] 默认场景分组准备完成: " f"scene={default_scene.scene_id}, group={default_group.id}, created={created}")

    for legacy_scene in _iter_legacy_scenes(Scene):
        _backfill_default_panel_group_items(
            VisionPanel,
            ResourceBinding,
            ResourceBindingScene,
            SceneReportGroupItem,
            default_group,
            legacy_scene,
        )

    print("[0014] 历史 default 报表分组回填完成")


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0007_alter_resourcebinding_resource_type_and_more"),
        ("vision", "0013_cleanup_legacy_non_default_panel_scene_bindings"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
