# Generated by Django 4.2.26 on 2026-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0014_backfill_default_scene_panel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionpanel',
            name='default_value_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='存储场景/系统级别的默认值覆盖配置', verbose_name='默认值覆盖'),
        ),
    ]
