# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0014_backfill_default_scene_panel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionpanel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
