#!/bin/sh
export PYTHONUTF8=1

remote="$1"
url="$2"

exec < /dev/tty

echo "正在触发AI CodeReview，请稍等片刻..."

SH=bkaidev.apigw.o.woa.com/prod
WSSH=prod-dot-scene-ws-dot-bkaidev-ng.bkapps-sz1.woa.com
FSH=bkaidev.woa.com

C:/Users/v_zzlgzhong/bkaidev/aidev_executable_2.exe review-code diff \
-tk "gGZTFd0EArUKe+n+yELD5u3GBvbJDPyPy60xtd/YcAEScMC0f9o6O3mcmGm4UHRO" \
--encrypted \
-sh $SH \
-crf codereviewer_openai \
--session_id 167e1c8c-cf6e-4f53-9fa6-b22b494c7ba7 \
-nsc -wssh $WSSH \
-fsh $FSH \
-rm $remote \
 \
-bac bkcodeai-vscode:0.2.9

if [ $? -ne 0 ]; then
    exit 1
fi
exit 0