# Generated by Django 3.2.18 on 2023-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_noticelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticelog",
            name="receivers",
            field=models.JSONField(blank=True, null=True, verbose_name="收件人"),
        ),
        migrations.AlterField(
            model_name="noticegroup",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="noticegroup",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="noticelog",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="noticelog",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
    ]
