# Generated by Django 3.2.18 on 2023-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_auto_20230907_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticelog",
            name="extra",
            field=models.TextField(blank=True, null=True, verbose_name="拓展信息"),
        ),
        migrations.AddField(
            model_name="noticelog",
            name="is_duplicate",
            field=models.BooleanField(default=False, verbose_name="是否重复"),
        ),
        migrations.AddField(
            model_name="noticelog",
            name="is_success",
            field=models.BooleanField(default=False, verbose_name="是否成功"),
        ),
        migrations.AddField(
            model_name="noticelog",
            name="trace_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Trace ID"),
        ),
    ]
