# Generated by Django 3.2.23 on 2024-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0004_auto_20230907_1906"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeLogV2",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relate_type",
                    models.CharField(
                        choices=[("risk", "风险"), ("error", "异常")], db_index=True, max_length=16, verbose_name="关联类型"
                    ),
                ),
                (
                    "relate_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="关联ID"),
                ),
                ("agg_key", models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="聚合标识")),
                ("msg_type", models.JSONField(default=list, verbose_name="消息类型")),
                ("receivers", models.JSONField(default=list, verbose_name="接收人")),
                ("title", models.TextField(blank=True, null=True, verbose_name="消息标题")),
                ("content", models.TextField(blank=True, null=True, verbose_name="消息内容")),
                ("create_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("schedule_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="发送时间")),
                ("schedule_result", models.BooleanField(blank=True, db_index=True, null=True, verbose_name="发送结果")),
                ("debug_info", models.TextField(blank=True, null=True, verbose_name="发送调试信息")),
            ],
            options={
                "verbose_name": "通知记录",
                "verbose_name_plural": "通知记录",
                "ordering": ["-id"],
                "index_together": {("relate_type", "agg_key", "schedule_at", "create_at")},
            },
        ),
    ]
