# Generated by Django 3.2.23 on 2025-03-07 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_noticelogv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticegroup',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='noticegroup',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='noticegroup',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='noticegroup',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
    ]
