# Generated by Django 4.2.19 on 2025-05-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20250307_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelogv2',
            name='relate_type',
            field=models.CharField(
                choices=[('risk', '风险'), ('error', '异常'), ('log_export', '日志导出')],
                db_index=True,
                max_length=16,
                verbose_name='关联类型',
            ),
        ),
    ]
