# Generated by Django 3.2.18 on 2023-07-03 09:23
import django
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "risk_id",
                    core.models.UUIDField(
                        default=core.models.UUIDField.get_default_value,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Risk ID",
                    ),
                ),
                ("event_content", models.TextField(blank=True, null=True, verbose_name="事件描述")),
                ("raw_event_id", models.CharField(db_index=True, max_length=255, verbose_name="原始事件ID")),
                (
                    "strategy",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='risks',
                        to='strategy_v2.strategy',
                        verbose_name='命中策略(ID)',
                    ),
                ),
                ("event_evidence", models.TextField(blank=True, null=True, verbose_name="事件证据")),
                ("event_data", models.JSONField(blank=True, null=True, verbose_name="事件拓展数据")),
                ("event_time", models.DateTimeField(db_index=True, verbose_name="事件发生时间")),
                (
                    "event_source",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="事件来源"),
                ),
                (
                    "operator",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="负责人"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("closed", "已关闭"), ("callback", "已回调"), ("new", "待处理"), ("dealing", "处理中")],
                        db_index=True,
                        default="new",
                        max_length=32,
                        verbose_name="Risk Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risk",
                "ordering": ["-event_time"],
                "index_together": {("strategy", "raw_event_id", "status")},
            },
        ),
    ]
