# Generated by Django 3.2.18 on 2023-07-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0002_alter_risk_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="event_type",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="事件类型"),
        ),
    ]
