# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - 审计中心 (BlueKing - Audit Center) available.
Copyright (C) 2023 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.
We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.18 on 2023-08-23 06:18

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0003_risk_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessApplication",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "id",
                    core.models.UUIDField(
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("sops_template_id", models.BigIntegerField(verbose_name="SOps Template ID")),
                ("need_approve", models.BooleanField(default=True, verbose_name="Need Approve")),
                (
                    "approve_service_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Approve Service ID"),
                ),
                ("approve_config", models.JSONField(blank=True, null=True, verbose_name="Approve Config")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("auto_close_risk", models.BooleanField(default=True, verbose_name="Auto Close Risk")),
            ],
            options={
                "verbose_name": "Process Application",
                "verbose_name_plural": "Process Application",
                "ordering": ["-updated_at"],
            },
        ),
    ]
