# Generated by Django 3.2.18 on 2023-08-29 07:58

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0004_auto_20230823_1418"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processapplication",
            name="auto_close_risk",
        ),
        migrations.AddField(
            model_name="risk",
            name="current_operator",
            field=models.JSONField(blank=True, default=list, max_length=64, null=True, verbose_name="Current Operator"),
        ),
        migrations.AddField(
            model_name="risk",
            name="origin_operator",
            field=models.JSONField(blank=True, default=list, max_length=64, null=True, verbose_name="Current Operator"),
        ),
        migrations.AddField(
            model_name="risk",
            name="rule_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Risk Rule ID"),
        ),
        migrations.AddField(
            model_name="risk",
            name="rule_version",
            field=models.IntegerField(blank=True, null=True, verbose_name="Risk Rule Version"),
        ),
        migrations.AddField(
            model_name="risk",
            name="ticket_history",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Risk Ticket History"),
        ),
        migrations.AlterField(
            model_name="risk",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "新"),
                    ("closed", "已关单"),
                    ("await_deal", "待处理"),
                    ("for_approve", "自动处理审批中"),
                    ("auto_process", "套餐处理中"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="Risk Status",
            ),
        ),
        migrations.CreateModel(
            name="RiskRule",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "id",
                    core.models.UUIDField(
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    core.models.UUIDField(
                        db_index=True,
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        verbose_name="Rule ID",
                    ),
                ),
                ("version", models.IntegerField(blank=True, null=True, verbose_name="版本号")),
                ("name", models.CharField(max_length=64, verbose_name="Risk Rule Name")),
                ("scope", models.JSONField(verbose_name="Rule Scope")),
                (
                    "pa_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True, verbose_name="Process Application ID"
                    ),
                ),
                ("pa_params", models.JSONField(blank=True, null=True, verbose_name="Process Application Params")),
                ("auto_close_risk", models.BooleanField(default=True, verbose_name="Auto Close Risk")),
                ("priority_index", models.IntegerField(default=0, verbose_name="Priority Index")),
            ],
            options={
                "verbose_name": "Risk Rule",
                "verbose_name_plural": "Risk Rule",
                "ordering": ["-updated_at"],
                "unique_together": {("rule_id", "version")},
                "index_together": {("priority_index", "rule_id", "version")},
            },
        ),
    ]
