# Generated by Django 3.2.18 on 2023-08-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0007_riskrule_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="notice_users",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Notice Users"),
        ),
        migrations.AddField(
            model_name="risk",
            name="risk_label",
            field=models.CharField(
                blank=True,
                choices=[("normal", "正常"), ("misreport", "误报")],
                default="normal",
                max_length=32,
                null=True,
                verbose_name="Risk Label",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Tags"),
        ),
    ]
