# Generated by Django 3.2.18 on 2023-09-04 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0008_auto_20230830_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskExperience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("risk_id", models.CharField(db_index=True, max_length=255, verbose_name="Risk ID")),
                ("content", models.TextField(verbose_name="Risk Experience Content")),
            ],
            options={
                "verbose_name": "Risk Experience",
                "verbose_name_plural": "Risk Experience",
                "ordering": ["-id"],
                "unique_together": {("risk_id", "created_at")},
            },
        ),
    ]
