# Generated by Django 3.2.18 on 2023-09-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0010_iam_migrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="processapplication",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Is Enabled"),
        ),
        migrations.AlterField(
            model_name="risk",
            name="origin_operator",
            field=models.JSONField(blank=True, default=list, max_length=64, null=True, verbose_name="Origin Operator"),
        ),
        migrations.AlterField(
            model_name="risk",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "新"),
                    ("await_deal", "待处理"),
                    ("for_approve", "自动处理审批中"),
                    ("auto_process", "套餐处理中"),
                    ("closed", "已关单"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="Risk Status",
            ),
        ),
    ]
