# Generated by Django 3.2.18 on 2023-09-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0011_auto_20230911_1209"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="riskexperience",
            unique_together=set(),
        ),
    ]
