# Generated by Django 3.2.18 on 2023-09-15 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0012_alter_riskexperience_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risk",
            name="ticket_history",
        ),
    ]
