# Generated by Django 3.2.18 on 2023-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0014_ticketnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="event_end_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="事件发生时间"),
        ),
    ]
