# Generated by Django 3.2.18 on 2023-09-19 08:22

from django.db import migrations, models

import services.web.risk.models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0017_auto_20230919_1622"),
    ]

    operations = [
        migrations.DeleteModel(name="RiskRule"),
        migrations.DeleteModel(name="ProcessApplication"),
    ]
