# Generated by Django 3.2.18 on 2023-09-20 03:39

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0018_remove_old"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessApplication",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uniq_id",
                    core.models.UUIDField(
                        default=core.models.UUIDField.get_default_value, max_length=64, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("sops_template_id", models.BigIntegerField(verbose_name="SOps Template ID")),
                ("need_approve", models.BooleanField(default=True, verbose_name="Need Approve")),
                (
                    "approve_service_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Approve Service ID"),
                ),
                ("approve_config", models.JSONField(blank=True, null=True, verbose_name="Approve Config")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Is Enabled")),
            ],
            options={
                "verbose_name": "Process Application",
                "verbose_name_plural": "Process Application",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="risk",
            name="rule_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Risk Rule ID"),
        ),
        migrations.CreateModel(
            name="RiskRule",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uniq_id",
                    core.models.UUIDField(
                        default=core.models.UUIDField.get_default_value, max_length=64, unique=True, verbose_name="UUID"
                    ),
                ),
                ("rule_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Rule ID")),
                ("version", models.IntegerField(blank=True, null=True, verbose_name="版本号")),
                ("name", models.CharField(max_length=64, verbose_name="Risk Rule Name")),
                ("scope", models.JSONField(verbose_name="Rule Scope")),
                (
                    "pa_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Process Application ID"),
                ),
                ("pa_params", models.JSONField(blank=True, null=True, verbose_name="Process Application Params")),
                ("auto_close_risk", models.BooleanField(default=True, verbose_name="Auto Close Risk")),
                ("priority_index", models.IntegerField(default=0, verbose_name="Priority Index")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Is Enabled")),
            ],
            options={
                "verbose_name": "Risk Rule",
                "verbose_name_plural": "Risk Rule",
                "ordering": ["-updated_at"],
                "unique_together": {("rule_id", "version")},
                "index_together": {("priority_index", "rule_id", "version")},
            },
        ),
    ]
