# Generated by Django 3.2.18 on 2023-09-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0019_auto_20230920_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processapplication",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="riskrule",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="Risk Rule Name"),
        ),
    ]
