# Generated by Django 3.2.18 on 2023-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0020_auto_20230926_1248"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("risk_id", models.CharField(db_index=True, max_length=255, verbose_name="Risk ID")),
                ("action", models.CharField(db_index=True, max_length=32, verbose_name="Action")),
                ("operator", models.CharField(db_index=True, max_length=255, verbose_name="Operator")),
                ("authorized_at", models.DateTimeField(auto_now_add=True, verbose_name="Authorized Time")),
            ],
            options={
                "verbose_name": "Ticket Permission",
                "verbose_name_plural": "Ticket Permission",
                "ordering": ["-id"],
                "unique_together": {("risk_id", "action", "operator")},
            },
        ),
    ]
