# Generated by Django 4.2.19 on 2025-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0013_auto_20250307_1329'),
        ('risk', '0024_auto_20250307_1329'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='risk',
            index_together={('strategy', 'raw_event_id', 'status'), ('strategy', 'event_time')},
        ),
    ]
