# Generated by Django 4.2.19 on 2025-07-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0027_alter_risk_index_together'),
        ('risk', '0027_alter_ticketpermission_unique_together_and_more'),
    ]

    operations = []
