# Generated by Django 4.2.23 on 2025-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0027_alter_risk_index_together'),
        ('risk', '0027_alter_ticketpermission_unique_together_and_more'),
    ]

    operations = []
