# Generated by Django 4.2.23 on 2025-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0029_remove_risk_tags_risk_tag_objs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='operator',
            field=models.JSONField(blank=True, null=True, verbose_name='责任人'),
        ),
    ]
