# Generated by Django 4.2.24 on 2025-10-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0030_alter_risk_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='tag_objs',
        ),
    ]
