# Generated by Django 4.2.26 on 2025-11-18 02:31

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0031_remove_risk_tag_objs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                (
                    'token',
                    core.models.UUIDField(
                        db_index=True,
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        unique=True,
                        verbose_name='订阅 Token',
                    ),
                ),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='配置名称')),
                (
                    'namespace',
                    models.CharField(db_index=True, default='default', max_length=64, verbose_name='命名空间'),
                ),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '风险事件订阅',
                'verbose_name_plural': '风险事件订阅',
                'ordering': ['-updated_at'],
            },
        ),
    ]
