# Generated by Django 4.2.26 on 2025-11-17 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import services.web.risk.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0020_merge_20251110_1718'),
        ('risk', '0031_remove_risk_tag_objs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRiskEvent',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'manual_event_id',
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name='Manual Risk Event ID'),
                ),
                ('event_content', models.TextField(blank=True, null=True, verbose_name='事件描述')),
                ('raw_event_id', models.CharField(db_index=True, max_length=255, verbose_name='原始事件ID')),
                ('event_evidence', models.TextField(blank=True, null=True, verbose_name='事件证据')),
                ('event_type', models.JSONField(blank=True, default=list, null=True, verbose_name='事件类型')),
                ('event_data', models.JSONField(blank=True, null=True, verbose_name='事件拓展数据')),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='事件发生时间')),
                ('event_end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='事件发生时间')),
                (
                    'event_source',
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='事件来源'),
                ),
                ('operator', models.JSONField(blank=True, null=True, verbose_name='责任人')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', '新'),
                            ('await_deal', '待处理'),
                            ('for_approve', '自动处理审批中'),
                            ('auto_process', '套餐处理中'),
                            ('closed', '已关单'),
                        ],
                        db_index=True,
                        default='new',
                        max_length=32,
                        verbose_name='Risk Status',
                    ),
                ),
                ('rule_id', models.BigIntegerField(blank=True, null=True, verbose_name='Risk Rule ID')),
                ('rule_version', models.IntegerField(blank=True, null=True, verbose_name='Risk Rule Version')),
                (
                    'origin_operator',
                    models.JSONField(
                        blank=True, default=list, max_length=64, null=True, verbose_name='Origin Operator'
                    ),
                ),
                (
                    'current_operator',
                    models.JSONField(
                        blank=True, default=list, max_length=64, null=True, verbose_name='Current Operator'
                    ),
                ),
                ('notice_users', models.JSONField(blank=True, default=list, null=True, verbose_name='Notice Users')),
                (
                    'risk_label',
                    models.CharField(
                        blank=True,
                        choices=[('normal', '正常'), ('misreport', '误报')],
                        default='normal',
                        max_length=32,
                        null=True,
                        verbose_name='Risk Label',
                    ),
                ),
                (
                    'last_operate_time',
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Operate Time'),
                ),
                ('title', models.TextField(blank=True, default=None, null=True, verbose_name='Risk Title')),
                (
                    'strategy',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='manual_risk_events',
                        to='strategy_v2.strategy',
                        verbose_name='命中策略(ID)',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Manual Risk Event',
                'verbose_name_plural': 'Manual Risk Event',
                'ordering': ['-event_time'],
                'index_together': {('strategy', 'raw_event_id', 'status'), ('strategy', 'event_time')},
            },
            bases=(services.web.risk.models.StrategyTagMixin, models.Model),
        ),
    ]
