# Generated by Django 4.2.26 on 2025-11-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0020_merge_20251110_1718'),
        ('risk', '0032_manualriskevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualriskevent',
            name='strategy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='manual_risk_events',
                to='strategy_v2.strategy',
                verbose_name='命中策略(ID)',
            ),
        ),
    ]
