# Generated by Django 4.2.26 on 2025-11-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0032_risk_event_subscription'),
        ('risk', '0033_alter_manualriskevent_strategy'),
    ]

    operations = []
