# Generated by Django 4.2.25 on 2025-11-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0034_merge_20251120_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualriskevent',
            options={'ordering': ['-event_time'], 'verbose_name': '手动事件存储', 'verbose_name_plural': '手动事件存储'},
        ),
    ]
