# Generated by Django 4.2.25 on 2025-11-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0035_alter_manualriskevent_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ManualRiskEvent",
            new_name="ManualEvent",
        ),
        migrations.RemoveField(
            model_name="manualevent",
            name="event_end_time",
        ),
    ]
