# Generated by Django 4.2.26 on 2025-12-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0032_risk_event_subscription'),
        ('risk', '0035_manualevent_manual_synced_risk_manual_synced'),
    ]

    operations = []
