# Generated by Django 4.2.25 on 2025-11-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0020_merge_20251110_1718'),
        ('risk', '0036_manualevent_remove_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualevent',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manual_events', to='strategy_v2.strategy', verbose_name='命中策略(ID)'),
        ),
    ]
