# Generated by Django 4.2.26 on 2025-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0037_alter_manualevent_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualevent',
            name='manual_synced',
            field=models.BooleanField(default=False, verbose_name='手动建的单是否已同步'),
        ),
        migrations.AddField(
            model_name='risk',
            name='manual_synced',
            field=models.BooleanField(default=True, verbose_name='手动建的单是否已同步'),
        ),
    ]
