# Generated by Django 4.2.26 on 2025-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0036_merge_20251204_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='责任人'),
        ),
    ]
