# Generated by Django 4.2.26 on 2026-01-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0021_strategy_source'),
        ('risk', '0039_alter_manualevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualevent',
            options={
                'ordering': ['-event_time'],
                'verbose_name': '手动事件存储',
                'verbose_name_plural': '手动事件存储',
            },
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='strategy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='manual_events',
                to='strategy_v2.strategy',
                verbose_name='命中策略(ID)',
            ),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
    ]
