# Generated by Django 4.2.26 on 2026-01-07 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0022_add_render_task_risk_report_auto_generate'),
        ('risk', '0039_alter_manualevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'risk',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='report',
                        serialize=False,
                        to='risk.risk',
                        verbose_name='关联风险',
                    ),
                ),
                ('content', models.TextField(blank=True, default='', verbose_name='报告内容')),
                (
                    'status',
                    models.CharField(
                        choices=[('auto', '自动生成'), ('manual', '人工编辑')],
                        default='auto',
                        max_length=20,
                        verbose_name='报告状态',
                    ),
                ),
            ],
            options={
                'verbose_name': '风险报告',
                'verbose_name_plural': '风险报告',
            },
        ),
        migrations.AlterModelOptions(
            name='manualevent',
            options={
                'ordering': ['-event_time'],
                'verbose_name': '手动事件存储',
                'verbose_name_plural': '手动事件存储',
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='auto_generate_report',
            field=models.BooleanField(default=True, help_text='开启后策略产生新风险时会自动生成报告', verbose_name='是否开启自动生成报告'),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='strategy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='manual_events',
                to='strategy_v2.strategy',
                verbose_name='命中策略(ID)',
            ),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', '待处理'),
                            ('processing', '处理中'),
                            ('completed', '已完成'),
                            ('failed', '失败'),
                            ('abandoned', '已放弃'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                        verbose_name='任务状态',
                    ),
                ),
                (
                    'version',
                    models.IntegerField(default=1, help_text='用于控制并发，确保同一版本的渲染任务一致性', verbose_name='版本号'),
                ),
                (
                    'render_task_id',
                    models.CharField(
                        blank=True,
                        help_text='调用渲染器服务后返回的任务ID，用于查询结果',
                        max_length=64,
                        null=True,
                        verbose_name='渲染器服务任务ID',
                    ),
                ),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                (
                    'risk',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='render_tasks',
                        to='risk.risk',
                        verbose_name='关联风险',
                    ),
                ),
            ],
            options={
                'verbose_name': '渲染任务',
                'verbose_name_plural': '渲染任务',
                'ordering': ['risk', '-version'],
                'unique_together': {('risk', 'version')},
                'index_together': {('status', 'created_at'), ('risk', 'status', 'version')},
            },
        ),
    ]
