# Generated by Django 4.2.26 on 2026-01-07 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0022_add_render_task_risk_report_auto_generate'),
        ('risk', '0039_alter_manualevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'risk',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='report',
                        serialize=False,
                        to='risk.risk',
                        verbose_name='关联风险',
                    ),
                ),
                ('content', models.TextField(blank=True, default='', verbose_name='报告内容')),
                (
                    'status',
                    models.CharField(
                        choices=[('auto', '自动生成'), ('manual', '人工编辑')],
                        default='auto',
                        max_length=20,
                        verbose_name='报告状态',
                    ),
                ),
            ],
            options={
                'verbose_name': '风险报告',
                'verbose_name_plural': '风险报告',
            },
        ),
        migrations.AlterModelOptions(
            name='manualevent',
            options={
                'ordering': ['-event_time'],
                'verbose_name': '手动事件存储',
                'verbose_name_plural': '手动事件存储',
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='auto_generate_report',
            field=models.BooleanField(default=True, help_text='开启后策略产生新风险时会自动生成报告', verbose_name='是否开启自动生成报告'),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='strategy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='manual_events',
                to='strategy_v2.strategy',
                verbose_name='命中策略(ID)',
            ),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(
                choices=[
                    ('stand_by', '录入中'),
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
    ]
