# Generated by Django 4.2.26 on 2026-01-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_riskreport_alter_manualevent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderTask',
        ),
    ]
