# Generated by Django 4.2.26 on 2026-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0041_delete_rendertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='auto_generate_report',
            field=models.BooleanField(default=True, help_text='开启后风险产生新事件时会自动生成报告', verbose_name='是否开启自动生成报告'),
        ),
    ]
