# Generated by Django 4.2.26 on 2026-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0042_alter_risk_auto_generate_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='has_report',
            field=models.BooleanField(
                db_index=True, default=False, help_text='任何流程为该风险生成报告后置为 True', verbose_name='是否已生成报告'
            ),
        ),
    ]
