# Generated by Django 4.2.26

from django.db import migrations, models

import services.web.risk.constants


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0042_alter_risk_auto_generate_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="display_status",
            field=models.CharField(
                choices=[
                    ("stand_by", "录入中"),
                    ("new", "新"),
                    ("await_deal", "待处理"),
                    ("processing", "处理中"),
                    ("for_approve", "自动处理审批中"),
                    ("auto_process", "套餐处理中"),
                    ("closed", "已关单"),
                ],
                db_index=True,
                default=services.web.risk.constants.RiskDisplayStatus["NEW"],
                max_length=32,
                verbose_name="Display Status",
            ),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', '新'),
                    ('await_deal', '待处理'),
                    ('for_approve', '自动处理审批中'),
                    ('auto_process', '套餐处理中'),
                    ('closed', '已关单'),
                ],
                db_index=True,
                default='new',
                max_length=32,
                verbose_name='Risk Status',
            ),
        ),
    ]
