# Generated by Django 4.2.26 on 2026-01-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_alter_manualevent_options_alter_manualevent_status_and_more'),
        ('risk', '0042_alter_risk_auto_generate_report'),
    ]

    operations = []
