# Generated by Django 4.2.26 on 2026-03-23 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0044_backfill_display_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NL2RiskFilterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('query', models.CharField(max_length=2048, verbose_name='查询文本')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                (
                    'status',
                    models.CharField(
                        choices=[('success', '成功'), ('parse_failed', '解析失败'), ('api_error', '接口异常')],
                        db_index=True,
                        default='success',
                        max_length=32,
                        verbose_name='状态',
                    ),
                ),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': 'NL2RiskFilter查询日志',
                'verbose_name_plural': 'NL2RiskFilter查询日志',
                'db_table': 'risk_nl2riskfilterlog',
                'ordering': ['-created_at'],
                'index_together': {('status', 'created_at')},
            },
        ),
    ]
