# Generated by Django 4.2.26 on 2026-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0046_remove_scene_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketpermission',
            index=models.Index(fields=['user', 'action', 'user_type', 'risk_id'], name='risk_tp_user_act_rid_idx'),
        ),
    ]
