# Generated by Django 4.2.26 on 2026-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0047_add_nl2riskfilterlog'),
        ('risk', '0047_alter_analyse_report_charset_utf8mb4'),
    ]

    operations = []
