# Generated by Django 4.2.26 on 2026-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0047_ticketpermission_risk_tp_user_act_rid_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(
                fields=['strategy', 'display_status', 'event_time'], name='idx_risk_strategy_status_time'
            ),
        ),
    ]
