# Generated by Django 4.2.26 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0047_add_nl2riskfilterlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketpermission",
            name="authorized_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Authorized Time",
            ),
        ),
    ]
