# Generated by Django 4.2.26 on 2026-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0048_risk_idx_risk_strategy_status_time"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticketpermission",
            index=models.Index(fields=["authorized_at", "id"], name="risk_tp_auth_id_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketnode",
            index=models.Index(fields=["status", "timestamp"], name="risk_tn_status_time_idx"),
        ),
    ]
