# Generated by Django 4.2.26 on 2026-03-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0048_merge_20260325_1943'),
        ('risk', '0048_ticketpermission_idx_authorized_at'),
    ]

    operations = []
