# Generated by Django 4.2.26 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0049_merge_20260601_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysereport",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict, help_text="报告生成失败原因等附加信息", verbose_name="额外信息"),
        ),
    ]
