# Generated by Django 4.2.26 on 2026-06-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0049_merge_20260601_1618'),
        ('risk', '0049_ticketpermission_auth_index_ticketnode_status_index'),
    ]

    operations = []
