# Generated by Django 4.2.26 on 2026-06-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0050_analysereport_extra_info"),
        ("risk", "0050_merge_20260601_1712"),
    ]

    operations = []
