# Generated by Django 4.2.26 on 2026-06-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0051_merge_20260603_1648"),
        ("risk", "0051_update_analyse_report_scenario_prompts"),
    ]

    operations = []
