# Generated by Django 4.2.26 on 2026-06-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0051_update_analyse_report_scenario_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysereport',
            name='title_generating',
            field=models.BooleanField(db_index=True, default=False, verbose_name='AI标题生成中'),
        ),
        migrations.AddField(
            model_name='analysereport',
            name='title_task_id',
            field=models.CharField(
                blank=True, db_index=True, default='', max_length=255, verbose_name='标题生成Celery任务ID'
            ),
        ),
    ]
