# Generated by Django 4.2.26 on 2026-06-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0052_merge_20260604_2111'),
        ('risk', '0053_update_analyse_report_scenario_prompt_content'),
    ]

    operations = []
