# Generated by Codex on 2026-06-17

import hashlib

from django.db import migrations, models


def backfill_query_hash(apps, schema_editor):
    nl2risk_filter_log = apps.get_model("risk", "NL2RiskFilterLog")
    batch = []
    for log in nl2risk_filter_log.objects.only("id", "query").iterator(chunk_size=1000):
        log.query_hash = hashlib.sha256((log.query or "").encode("utf-8")).hexdigest()
        batch.append(log)
        if len(batch) >= 1000:
            nl2risk_filter_log.objects.bulk_update(batch, ["query_hash"], batch_size=1000)
            batch = []
    if batch:
        nl2risk_filter_log.objects.bulk_update(batch, ["query_hash"], batch_size=1000)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("risk", "0053_update_analyse_report_scenario_prompt_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="nl2riskfilterlog",
            name="query_hash",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="查询文本哈希"),
        ),
        migrations.RunPython(backfill_query_hash, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="nl2riskfilterlog",
            index=models.Index(
                fields=["created_by", "status", "query_hash", "id"],
                name="risk_nl2log_user_st_qh_id",
            ),
        ),
    ]
