# Generated by Django 4.2.26 on 2026-06-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0054_merge_20260616_1542'),
        ('risk', '0054_nl2riskfilterlog_query_hash'),
    ]

    operations = []
