# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0054_nl2riskfilterlog_query_hash"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticketpermission",
            index=models.Index(
                fields=["user", "action", "user_type", "authorized_at", "risk_id"],
                name="risk_tp_user_act_auth_rid_idx",
            ),
        ),
    ]
