# Generated by Django 4.2.26 on 2026-06-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0049_ticketpermission_auth_index_ticketnode_status_index'),
        ('risk', '0055_ticketpermission_user_action_authorized_index'),
    ]

    operations = []
