# Generated by Django 4.2.26 on 2026-07-07 15:17

import time

from django.db import migrations, models
from django.utils import timezone

BATCH_SIZE = 5000
PROGRESS_INTERVAL_RISKS = 50000
BACKFILL_STATE = {}
REQUIRED_RISK_INDEXES = {"risk_level_time_id_idx"}
REQUIRED_PERSON_INDEXES = {"risk_person_rid_type_user_idx", "risk_person_updated_id_idx"}
PERSON_RELATION_FIELDS = {
    "operator": "operator",
    "current_operator": "current_operator",
    "notice_users": "notice_user",
}


class MigrationRiskLevelOrder(models.IntegerChoices):
    UNKNOWN = -1, "未知"
    LOW = 0, "低"
    MIDDLE = 1, "中"
    HIGH = 2, "高"


DEFAULT_RISK_LEVEL_ORDER = MigrationRiskLevelOrder.UNKNOWN.value


def normalize_users(users):
    if not users:
        return []
    values = [users] if isinstance(users, str) else users
    normalized = []
    for user in values:
        if user is None:
            continue
        for comma_part in str(user).split(","):
            normalized.extend(comma_part.split(";"))
    return list(dict.fromkeys(user.strip() for user in normalized if user and user.strip()))


def build_person_index_objs(risk_person_index_model, risk, now):
    objs = []
    for field_name, relation_type in PERSON_RELATION_FIELDS.items():
        for user in normalize_users(getattr(risk, field_name, None)):
            objs.append(
                risk_person_index_model(
                    risk_id=risk.risk_id,
                    relation_type=relation_type,
                    user=user,
                    created_at=now,
                    updated_at=now,
                )
            )
    return objs


def process_batch(risk_person_index_model, batch, db_alias):
    now = timezone.now()
    person_index_creates = []

    for risk in batch:
        person_index_creates.extend(build_person_index_objs(risk_person_index_model, risk, now))

    if person_index_creates:
        risk_person_index_model.objects.using(db_alias).bulk_create(
            person_index_creates, batch_size=BATCH_SIZE, ignore_conflicts=True
        )

    return len(batch), len(person_index_creates)


def format_progress(processed, expected):
    if not expected:
        return str(processed)
    percent = processed * 100 / expected
    return f"{processed}/{expected} ({percent:.1f}%)"


def backfill_risk_level_snapshots(risk_model, strategy_model, schema_editor):
    """
    风险等级快照用单条 SQL 回填。

    这里刻意不通过 ORM 分批 bulk_update：
    - 风险行接近百万级时，Python 对象构造和多轮 UPDATE 成本高；
    - 该 RunPython 在 risk_level 相关索引创建前执行，避免边更新边维护新增索引；
    - LEFT JOIN 能覆盖历史孤儿 strategy_id，孤儿风险等级置空、排序值置为 -1。
    """

    db_alias = schema_editor.connection.alias
    quote_name = schema_editor.connection.ops.quote_name
    risk_table = quote_name(risk_model._meta.db_table)
    strategy_table = quote_name(strategy_model._meta.db_table)
    risk_count = risk_model.objects.using(db_alias).count()
    now = timezone.now()
    started_at = time.monotonic()

    print(
        "[backfill_risk_level_snapshots] "
        f"start risks={risk_count}, risk_table={risk_model._meta.db_table}, "
        f"strategy_table={strategy_model._meta.db_table}",
        flush=True,
    )

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE {risk_table} AS risk
            LEFT JOIN {strategy_table} AS strategy
                ON risk.{quote_name("strategy_id")} = strategy.{quote_name("strategy_id")}
            SET
                risk.{quote_name("risk_level")} = strategy.{quote_name("risk_level")},
                risk.{quote_name("risk_level_order")} = CASE strategy.{quote_name("risk_level")}
                    WHEN 'LOW' THEN {MigrationRiskLevelOrder.LOW.value}
                    WHEN 'MIDDLE' THEN {MigrationRiskLevelOrder.MIDDLE.value}
                    WHEN 'HIGH' THEN {MigrationRiskLevelOrder.HIGH.value}
                    ELSE {DEFAULT_RISK_LEVEL_ORDER}
                END,
                risk.{quote_name("updated_at")} = %s
            """,
            [now],
        )
    print(
        f"[backfill_risk_level_snapshots] done risks={risk_count}, elapsed={time.monotonic() - started_at:.1f}s",
        flush=True,
    )
    return risk_count


def print_person_index_progress(total_risks, expected_risks, total_person_indexes, started_at, *, prefix="progress"):
    print(
        "[backfill_person_indexes] "
        f"{prefix} risks={format_progress(total_risks, expected_risks)}, "
        f"person_indexes={total_person_indexes}, elapsed={time.monotonic() - started_at:.1f}s",
        flush=True,
    )


def backfill_person_indexes(risk_model, risk_person_index_model, db_alias, expected_risks=None):
    """
    人员索引仍需解析 JSON，保留 Python 分批插入。

    该步骤在 RiskPersonIndex 索引和唯一约束创建前执行，避免大批量插入时逐行维护二级索引。
    """

    batch = []
    total_risks = 0
    total_person_indexes = 0
    started_at = time.monotonic()
    next_progress_risks = PROGRESS_INTERVAL_RISKS

    print(
        "[backfill_person_indexes] "
        f"start risks={expected_risks or 'unknown'}, batch_size={BATCH_SIZE}, "
        f"progress_interval={PROGRESS_INTERVAL_RISKS}",
        flush=True,
    )

    queryset = (
        risk_model.objects.using(db_alias)
        .only("risk_id", "operator", "current_operator", "notice_users")
        .order_by("risk_id")
    )
    for risk in queryset.iterator(chunk_size=BATCH_SIZE):
        batch.append(risk)
        if len(batch) >= BATCH_SIZE:
            risk_count, person_index_count = process_batch(risk_person_index_model, batch, db_alias)
            total_risks += risk_count
            total_person_indexes += person_index_count
            while total_risks >= next_progress_risks:
                print_person_index_progress(total_risks, expected_risks, total_person_indexes, started_at)
                next_progress_risks += PROGRESS_INTERVAL_RISKS
            batch = []

    if batch:
        risk_count, person_index_count = process_batch(risk_person_index_model, batch, db_alias)
        total_risks += risk_count
        total_person_indexes += person_index_count

    print_person_index_progress(total_risks, expected_risks, total_person_indexes, started_at, prefix="done")
    return total_risks, total_person_indexes


def count_risk_level_snapshot_mismatches(risk_model, strategy_model, schema_editor):
    quote_name = schema_editor.connection.ops.quote_name
    risk_table = quote_name(risk_model._meta.db_table)
    strategy_table = quote_name(strategy_model._meta.db_table)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM {risk_table} AS risk
            LEFT JOIN {strategy_table} AS strategy
                ON risk.{quote_name("strategy_id")} = strategy.{quote_name("strategy_id")}
            WHERE NOT (
                (
                    risk.{quote_name("risk_level")} = strategy.{quote_name("risk_level")}
                    OR (
                        risk.{quote_name("risk_level")} IS NULL
                        AND strategy.{quote_name("risk_level")} IS NULL
                    )
                )
                AND risk.{quote_name("risk_level_order")} = CASE strategy.{quote_name("risk_level")}
                    WHEN 'LOW' THEN {MigrationRiskLevelOrder.LOW.value}
                    WHEN 'MIDDLE' THEN {MigrationRiskLevelOrder.MIDDLE.value}
                    WHEN 'HIGH' THEN {MigrationRiskLevelOrder.HIGH.value}
                    ELSE {DEFAULT_RISK_LEVEL_ORDER}
                END
            )
            """
        )
        return cursor.fetchone()[0]


def get_constraints(model, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(cursor, model._meta.db_table)


def has_columns_constraint(constraints, columns, *, unique=None, index=None):
    for constraint in constraints.values():
        if constraint.get("columns") != columns:
            continue
        if unique is not None and constraint.get("unique") != unique:
            continue
        if index is not None and constraint.get("index") != index:
            continue
        return True
    return False


def backfill_risk_snapshots_and_person_index(apps, schema_editor):
    """
    首次构建风险等级快照和人员检索索引。

    部署假设：migration 执行期间旧版本写风险链路已停止。若发布平台允许旧实例继续写入，
    迁移完成并切到新代码后需要执行 backfill_risk_person_index --fix 兜底校准。
    """

    risk_model = apps.get_model("risk", "Risk")
    risk_person_index_model = apps.get_model("risk", "RiskPersonIndex")
    strategy_model = apps.get_model("strategy_v2", "Strategy")
    db_alias = schema_editor.connection.alias
    started_at = time.monotonic()

    print("[backfill_risk_snapshots_and_person_index] start", flush=True)

    snapshot_risks = backfill_risk_level_snapshots(risk_model, strategy_model, schema_editor)
    person_index_risks, total_person_indexes = backfill_person_indexes(
        risk_model, risk_person_index_model, db_alias, expected_risks=snapshot_risks
    )
    BACKFILL_STATE.update(
        {
            "risk_snapshots": snapshot_risks,
            "person_index_risks": person_index_risks,
            "person_indexes": total_person_indexes,
        }
    )

    print(
        "[backfill_risk_snapshots_and_person_index] "
        "done "
        f"risk_snapshots={snapshot_risks}, "
        f"person_index_risks={person_index_risks}, "
        f"person_indexes={total_person_indexes}, "
        f"elapsed={time.monotonic() - started_at:.1f}s",
        flush=True,
    )


def check_risk_0057_post_migration(apps, schema_editor):
    """
    输出 0057 迁移后的轻量结论。

    这里不主动 raise：本迁移 atomic=False，如果最终检查阶段抛错，数据库可能已经完成大部分
    schema/data 变更但 migration 未记录成功，恢复成本高。异常情况通过 WARN 和关键计数暴露。
    """

    started_at = time.monotonic()
    risk_model = apps.get_model("risk", "Risk")
    risk_person_index_model = apps.get_model("risk", "RiskPersonIndex")
    strategy_model = apps.get_model("strategy_v2", "Strategy")
    db_alias = schema_editor.connection.alias

    risk_count = risk_model.objects.using(db_alias).count()
    person_index_count = risk_person_index_model.objects.using(db_alias).count()
    expected_person_indexes = BACKFILL_STATE.get("person_indexes")
    risk_level_mismatches = count_risk_level_snapshot_mismatches(risk_model, strategy_model, schema_editor)

    risk_constraints = get_constraints(risk_model, schema_editor)
    person_constraints = get_constraints(risk_person_index_model, schema_editor)
    missing_schema_items = [
        f"risk.{index_name}" for index_name in sorted(REQUIRED_RISK_INDEXES) if index_name not in risk_constraints
    ]
    missing_schema_items.extend(
        f"risk_person_index.{index_name}"
        for index_name in sorted(REQUIRED_PERSON_INDEXES)
        if index_name not in person_constraints
    )
    if not has_columns_constraint(risk_constraints, ["risk_level"], index=True):
        missing_schema_items.append("risk.risk_level_db_index")
    if not has_columns_constraint(person_constraints, ["relation_type", "user", "risk_id"], unique=True):
        missing_schema_items.append("risk_person_index.relation_type_user_risk_id_unique")

    person_index_count_matched = expected_person_indexes is None or person_index_count == expected_person_indexes
    status = "OK" if risk_level_mismatches == 0 and person_index_count_matched and not missing_schema_items else "WARN"
    expected_person_index_text = "unknown" if expected_person_indexes is None else expected_person_indexes

    print(
        "[risk_0057_post_migration_check] "
        f"conclusion status={status}, risks={risk_count}, "
        f"person_indexes={person_index_count}, expected_person_indexes={expected_person_index_text}, "
        f"person_index_count_matched={person_index_count_matched}, "
        f"risk_level_mismatches={risk_level_mismatches}, "
        f"missing_schema_items={missing_schema_items}, elapsed={time.monotonic() - started_at:.1f}s",
        flush=True,
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('risk', '0056_merge_20260618_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPersonIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('risk_id', models.CharField(max_length=255, verbose_name='Risk ID')),
                (
                    'relation_type',
                    models.CharField(
                        choices=[('operator', '责任人'), ('current_operator', '当前处理人'), ('notice_user', '关注人')],
                        max_length=32,
                        verbose_name='Relation Type',
                    ),
                ),
                ('user', models.CharField(max_length=255, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Risk Person Index',
                'verbose_name_plural': 'Risk Person Index',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(
                blank=True,
                choices=[('HIGH', '高'), ('MIDDLE', '中'), ('LOW', '低')],
                default=None,
                max_length=16,
                null=True,
                verbose_name='Risk Level',
            ),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_level_order',
            field=models.IntegerField(
                choices=MigrationRiskLevelOrder.choices,
                default=DEFAULT_RISK_LEVEL_ORDER,
                verbose_name='Risk Level Order',
            ),
        ),
        # 数据量较大时，先回填再创建新增索引/唯一约束，避免回填期间逐行维护二级索引。
        migrations.RunPython(
            backfill_risk_snapshots_and_person_index,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(
                blank=True,
                choices=[('HIGH', '高'), ('MIDDLE', '中'), ('LOW', '低')],
                db_index=True,
                default=None,
                max_length=16,
                null=True,
                verbose_name='Risk Level',
            ),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_level_order', 'event_time', 'risk_id'], name='risk_level_time_id_idx'),
        ),
        migrations.AddIndex(
            model_name='riskpersonindex',
            index=models.Index(fields=['risk_id', 'relation_type', 'user'], name='risk_person_rid_type_user_idx'),
        ),
        migrations.AddIndex(
            model_name='riskpersonindex',
            index=models.Index(fields=['updated_at', 'id'], name='risk_person_updated_id_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskpersonindex',
            unique_together={('relation_type', 'user', 'risk_id')},
        ),
        migrations.RunPython(
            check_risk_0057_post_migration,
            migrations.RunPython.noop,
        ),
    ]
