# Generated by Django 4.2.26 on 2026-06-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0055_merge_20260617_1047'),
        ('risk', '0056_merge_20260618_1700'),
    ]

    operations = []
