# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0056_merge_20260618_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
