# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0056_merge_20260618_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='analysereportscenario',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='processapplication',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='riskeventsubscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='riskexperience',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='riskrule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
