# Generated by Django 4.2.30
"""
软删除改造性能修复：
is_deleted 无索引导致 ListStrategy risk_count 关联子查询的
(strategy_id, event_time) 覆盖索引失效（Using index → Using where 回表），
staging 实测大数据量策略放大 17.86x（27.6ms → 492.8ms）。

加复合索引 (strategy_id, is_deleted, event_time) 恢复 index-only scan。
字段顺序依据最左前缀原则：等值(strategy_id) + 等值(is_deleted) + 范围(event_time)。
MySQL 8.0 创建二级索引默认 INPLACE，不锁表。
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0057_risk_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(
                fields=['strategy', 'is_deleted', 'event_time'], name='idx_risk_strategy_isdel_time'
            ),
        ),
    ]
