# Generated by Django 4.2.26 on 2026-09-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0058_risk_idx_strategy_isdel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapplication',
            name='approve_service_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Approve Service ID'),
        ),
    ]
