# Generated by Django 4.2.30 on 2026-08-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0026_add_multi_rule_support'),
        ('risk', '0058_risk_idx_strategy_isdel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualevent',
            name='risk_guidance',
            field=models.TextField(blank=True, help_text='处理指引（实例化）', null=True, verbose_name='Risk Guidance'),
        ),
        migrations.AddField(
            model_name='manualevent',
            name='risk_hazard',
            field=models.TextField(blank=True, help_text='风险危害描述（实例化）', null=True, verbose_name='Risk Hazard'),
        ),
        migrations.AddField(
            model_name='manualevent',
            name='risk_level',
            field=models.CharField(blank=True, help_text='风险等级（实例化）', max_length=16, null=True, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='manualevent',
            name='strategy_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联的发现规则', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manual_events', to='strategy_v2.strategyrule', verbose_name='Strategy Rule'),
        ),
        migrations.AddField(
            model_name='risk',
            name='confirmer',
            field=models.JSONField(blank=True, default=list, help_text='确认人用户名列表（仅全局策略）', verbose_name='Confirmer'),
        ),
        migrations.AddField(
            model_name='risk',
            name='dispatch_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='命中的分派规则（仅全局策略）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='risks', to='strategy_v2.dispatchrule', verbose_name='Dispatch Rule'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_guidance',
            field=models.TextField(blank=True, help_text='处理指引（实例化）', null=True, verbose_name='Risk Guidance'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_hazard',
            field=models.TextField(blank=True, help_text='风险危害描述（实例化）', null=True, verbose_name='Risk Hazard'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(blank=True, help_text='风险等级（实例化）', max_length=16, null=True, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='risk',
            name='strategy_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='命中的发现规则', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='risks', to='strategy_v2.strategyrule', verbose_name='Strategy Rule'),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='status',
            field=models.CharField(choices=[('new', '新'), ('pending_confirm', '待确认'), ('await_deal', '待处理'), ('for_approve', '自动处理审批中'), ('auto_process', '套餐处理中'), ('closed', '已关单')], db_index=True, default='new', max_length=32, verbose_name='Risk Status'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='display_status',
            field=models.CharField(choices=[('stand_by', '录入中'), ('new', '新'), ('pending_confirm', '待确认'), ('await_deal', '待处理'), ('processing', '处理中'), ('for_approve', '自动处理审批中'), ('auto_process', '套餐处理中'), ('closed', '已关单')], db_index=True, default='new', max_length=32, verbose_name='Display Status'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('new', '新'), ('pending_confirm', '待确认'), ('await_deal', '待处理'), ('for_approve', '自动处理审批中'), ('auto_process', '套餐处理中'), ('closed', '已关单')], db_index=True, default='new', max_length=32, verbose_name='Risk Status'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(
                fields=['strategy_rule', 'is_deleted', 'event_time'],
                name='idx_risk_srule_isdel_time',
            ),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(
                fields=['display_status', 'is_deleted', 'last_operate_time'],
                name='idx_risk_dstatus_isdel_time',
            ),
        ),
    ]
