# Generated by Django 4.2.26 on 2026-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0065_alter_risk_longtext_charset_utf8mb4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapplication',
            name='approve_service_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Approve Service ID'),
        ),
    ]
