# Generated by Django 4.2.19 on 2025-06-11 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vision', '0007_alter_visionpanel_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('tool_uid', models.CharField(db_index=True, max_length=64, verbose_name='工具UID')),
                ('tag_id', models.BigIntegerField(verbose_name='Tag ID')),
            ],
            options={
                'verbose_name': 'Tool Tag',
                'verbose_name_plural': 'Tool Tag',
                'unique_together': {('tool_uid', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('namespace', models.CharField(db_index=True, max_length=255, verbose_name='命名空间')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='工具名称')),
                (
                    'uid',
                    core.models.UUIDField(
                        db_index=True,
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        verbose_name='工具UID',
                    ),
                ),
                ('version', models.IntegerField(db_index=True, verbose_name='版本')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='工具描述')),
                (
                    'tool_type',
                    models.CharField(
                        choices=[('data_search', '数据查询'), ('api', 'API'), ('bk_vision', 'BK Vision')],
                        max_length=16,
                        verbose_name='工具类型',
                    ),
                ),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='工具配置')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tool',
                'ordering': ['namespace', '-updated_at'],
                'unique_together': {('uid', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DataSearchToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'data_search_config_type',
                    models.CharField(
                        choices=[('simple', '简易模式'), ('sql', 'SQL模式')], max_length=32, verbose_name='数据检索类型'
                    ),
                ),
                ('sql', models.TextField(blank=True, null=True, verbose_name='检索SQL')),
                (
                    'tool',
                    models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tool.tool'),
                ),
            ],
            options={
                'verbose_name': 'Data Search Tool Config',
                'verbose_name_plural': 'Data Search Tool Config',
            },
        ),
        migrations.CreateModel(
            name='BkvisionToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'panel',
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='vision.visionpanel'
                    ),
                ),
                (
                    'tool',
                    models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tool.tool'),
                ),
            ],
            options={
                'verbose_name': 'Bkvision Tool Config',
                'verbose_name_plural': 'Bkvision Tool Config',
            },
        ),
    ]
