# Generated by Django 4.2.19 on 2025-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='用户名')),
            ],
            options={
                'verbose_name': 'Auth User',
                'verbose_name_plural': 'Auth User',
            },
        ),
        migrations.RemoveField(
            model_name='tool',
            name='auth_user_groups',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='auth_users',
        ),
        migrations.AddField(
            model_name='tool',
            name='auth_users',
            field=models.ManyToManyField(
                blank=True, related_name='authorized_tools', to='tool.authuser', verbose_name='授权用户'
            ),
        ),
    ]
