# Generated by Django 4.2.19 on 2025-06-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_alter_visionpanel_scenario'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkvisiontoolconfig',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vision.visionpanel'),
        ),
        migrations.AlterField(
            model_name='bkvisiontoolconfig',
            name='tool',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='bkvision_config', to='tool.tool'
            ),
        ),
        migrations.AlterField(
            model_name='datasearchtoolconfig',
            name='tool',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='data_search_config', to='tool.tool'
            ),
        ),
    ]
