# Generated by Django 4.2.19 on 2025-06-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='auth_user_groups',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='auth_users',
        ),
    ]
