# Generated by Django 4.2.23 on 2025-08-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_alter_visionpanel_name'),
        ('tool', '0002_alter_bkvisiontoolconfig_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkvisiontoolconfig',
            name='panel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name='tools', to='vision.visionpanel'
            ),
        ),
    ]
