# Generated by Django 4.2.23 on 2025-08-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_bkvisiontoolconfig_panel'),
        ('tool', '0003_tool_permission_owner'),
    ]

    operations = []
