# Generated by Django 4.2.24 on 2025-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_merge_20250821_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkvisiontoolconfig',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='bkvision更新时间'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_bkvision',
            field=models.BooleanField(default=False, verbose_name='是否更新BkVision工具'),
        ),
    ]
