# Generated by Django 4.2.25 on 2025-10-27 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_merge_20250821_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkvisiontoolconfig',
            name='updated_time',
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='bkvision更新时间'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_bkvision',
            field=models.BooleanField(default=False, verbose_name='是否更新BkVision工具'),
        ),
    ]
