# Generated by Django 4.2.25 on 2025-10-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_bkvisiontoolconfig_updated_time_tool_is_bkvision'),
        ('tool', '0005_update_drill_config_to_list'),
    ]

    operations = []
