# Generated by Django 4.2.25 on 2025-10-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_update_drill_config_to_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkvisiontoolconfig',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='bkvision更新时间'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_bkvision',
            field=models.BooleanField(default=False, verbose_name='是否更新BkVision工具'),
        ),
    ]
