# Generated by Django 4.2.19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0007_update_bkvisiontoolconfig_updated_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32, null=True, verbose_name="创建者"
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32, null=True, verbose_name="修改者"
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=64, verbose_name="Username")),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="tool.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Favorite",
                "verbose_name_plural": "Tool Favorite",
                "unique_together": {("tool", "username")},
            },
        ),
    ]
