# Generated by Django 4.2.26 on 2026-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_update_bkvisiontoolconfig_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='工具描述'),
        ),
    ]
