# Generated by Django 4.2.26 on 2026-01-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_add_tool_favorite'),
        ('tool', '0008_alter_tool_description'),
    ]

    operations = []
