# Generated by Django 4.2.26 on 2026-02-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_merge_20260130_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('uid', 'version', 'name')},
        ),
    ]
