# Generated by Django 4.2.26 on 2026-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_alter_tool_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='scene_id',
            field=models.IntegerField(
                blank=True, db_index=True, help_text='仅场景级工具需要，关联 Scene.scene_id', null=True, verbose_name='所属场景ID'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='scope_type',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='平台级(platform)/场景级(scene)，为空表示存量工具',
                max_length=32,
                verbose_name='归属级别',
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(
                blank=True, default='', help_text='仅平台级工具需要，published/unpublished', max_length=32, verbose_name='上架状态'
            ),
        ),
    ]
