# Generated by Django 4.2.26 on 2026-04-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_add_scope_fields_to_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='scene_id',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='scope_type',
        ),
    ]
