# Generated by Django 4.2.26 on 2026-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_change_tool_status_default_to_unpublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(
                choices=[
                    ('data_search', '数据查询'),
                    ('api', 'API'),
                    ('bk_vision', 'BK Vision'),
                    ('smart_page', '智能页面'),
                ],
                max_length=16,
                verbose_name='工具类型',
            ),
        ),
    ]
