# Generated by Django 4.2.26 on 2026-04-28 06:38

from django.db import migrations
from django.db.models import Count


def validate_no_duplicate_uid_version(apps, schema_editor):
    tool = apps.get_model('tool', 'Tool')
    duplicates = list(
        tool.objects.values('uid', 'version')
        .annotate(row_count=Count('id'))
        .filter(row_count__gt=1)
        .order_by('uid', 'version')[:20]
    )
    if duplicates:
        detail = ", ".join(f"{item['uid']}@v{item['version']}({item['row_count']})" for item in duplicates)
        raise RuntimeError(
            "Cannot restore Tool unique_together=(uid, version); duplicate rows exist: %s. "
            "Please clean duplicate test data before running this migration." % detail
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_alter_tool_tool_type'),
    ]

    operations = [
        migrations.RunPython(validate_no_duplicate_uid_version, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('uid', 'version')},
        ),
    ]
