# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_add_is_show_to_input_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
