# Generated by Django 4.2.26 on 2025-12-15 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LogDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                (
                    'source_id',
                    models.CharField(
                        db_index=True,
                        help_text='英文标识，如 audit_log, operation_log',
                        max_length=64,
                        unique=True,
                        verbose_name='数据源标识',
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='数据源名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                (
                    'namespace',
                    models.CharField(db_index=True, default='default', max_length=64, verbose_name='命名空间'),
                ),
                (
                    'bkbase_table_id',
                    models.CharField(
                        help_text='BKBase 结果表 ID，如 591_bkaudit_event', max_length=255, verbose_name='BKBase 表 ID'
                    ),
                ),
                (
                    'storage_type',
                    models.CharField(
                        choices=[('hdfs', 'HDFS'), ('doris', 'Doris')],
                        default='doris',
                        help_text='BKBase 存储类型',
                        max_length=32,
                        verbose_name='存储类型',
                    ),
                ),
                (
                    'required_filter_fields',
                    models.JSONField(
                        default=list,
                        help_text="订阅配置项选择此数据源时，筛选条件中必须包含的字段列表，如 ['system_id', 'namespace']",
                        verbose_name='必须筛选字段',
                    ),
                ),
                (
                    'time_field',
                    models.CharField(
                        default='dtEventTimeStamp',
                        help_text='用于时间范围筛选的字段名',
                        max_length=64,
                        verbose_name='时间字段',
                    ),
                ),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '日志数据源',
                'verbose_name_plural': '日志数据源',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='配置描述')),
                (
                    'token',
                    core.models.UUIDField(
                        db_index=True,
                        default=core.models.UUIDField.get_default_value,
                        max_length=64,
                        unique=True,
                        verbose_name='订阅 Token',
                    ),
                ),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '日志订阅配置',
                'verbose_name_plural': '日志订阅配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('name', models.CharField(help_text='配置项的描述性名称', max_length=128, verbose_name='配置项名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                (
                    'condition',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='WhereCondition 格式的筛选条件，必须包含所有关联数据源的必须筛选字段',
                        verbose_name='筛选条件',
                    ),
                ),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                (
                    'data_sources',
                    models.ManyToManyField(
                        help_text='选择一个或多个数据源',
                        related_name='subscription_items',
                        to='log_subscription.logdatasource',
                        verbose_name='数据源',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='log_subscription.logsubscription',
                        verbose_name='订阅配置',
                    ),
                ),
            ],
            options={
                'verbose_name': '日志订阅配置项',
                'verbose_name_plural': '日志订阅配置项',
                'ordering': ['subscription', 'order', '-created_at'],
            },
        ),
    ]
