# Generated by Django 4.2.27 on 2026-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_subscription', '0003_init_field_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdatasource',
            name='required_filter_fields',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="订阅配置项选择此数据源时，筛选条件中必须包含的字段列表，如 ['system_id', 'namespace']",
                verbose_name='必须筛选字段',
            ),
        ),
    ]
