# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_subscription', '0004_alter_logdatasource_required_filter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsubscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
