# Generated by Django 3.2.12 on 2023-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0004_auto_20220923_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="auth_rt",
            field=models.BooleanField(default=False, verbose_name="已授权RT"),
        ),
        migrations.AddField(
            model_name="collectorplugin",
            name="extra_fields",
            field=models.JSONField(default=list, null=True, verbose_name="额外字段"),
        ),
        migrations.AddField(
            model_name="collectorplugin",
            name="plugin_scene",
            field=models.CharField(default="collector", max_length=24, verbose_name="插件场景"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="collector_config_id",
            field=models.IntegerField(db_index=True, verbose_name="BK-LOG 采集项ID"),
        ),
    ]
