# Generated by Django 3.2.12 on 2023-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0006_auto_20230228_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="source_platform",
            field=models.CharField(
                choices=[("bk_base", "计算平台"), ("bk_log", "日志平台")],
                db_index=True,
                default="bk_log",
                max_length=64,
                verbose_name="数据来源",
            ),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="bk_data_id",
            field=models.IntegerField(null=True, unique=True, verbose_name="DATAID"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="collector_config_id",
            field=models.IntegerField(db_index=True, unique=True, verbose_name="BK-LOG 采集项ID"),
        ),
    ]
