# Generated by Django 3.2.12 on 2023-05-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0007_auto_20230307_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="bkbase_hdfs_processing_id",
            field=models.CharField(max_length=255, null=True, verbose_name="BKBase HDFS Processing ID"),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="bkbase_hdfs_table_id",
            field=models.CharField(max_length=255, null=True, verbose_name="BKBase HDFS Table ID"),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="hdfs_status",
            field=models.CharField(
                choices=[("closed", "已关闭"), ("running", "运行中"), ("failed", "失败"), ("preparing", "启动中")],
                default="closed",
                max_length=32,
                verbose_name="HDFS Status",
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="storage_type",
            field=models.CharField(
                choices=[("__all__", "All"), ("hdfs", "HDFS"), ("redis", "Redis")],
                db_index=True,
                default="redis",
                max_length=32,
                verbose_name="Storage Type",
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="status",
            field=models.CharField(
                choices=[("closed", "已关闭"), ("running", "运行中"), ("failed", "失败"), ("preparing", "启动中")],
                db_index=True,
                default="closed",
                max_length=32,
                verbose_name="状态",
            ),
        ),
    ]
