# Generated by Django 3.2.18 on 2023-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0008_auto_20230517_1640"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorplugin",
            name="bkbase_processing_id",
            field=models.CharField(max_length=255, null=True, verbose_name="清洗"),
        ),
        migrations.AddField(
            model_name="collectorplugin",
            name="bkbase_table_id",
            field=models.CharField(max_length=255, null=True, verbose_name="清洗"),
        ),
        migrations.AddField(
            model_name="collectorplugin",
            name="has_storage",
            field=models.BooleanField(default=False, verbose_name="是否有存储"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="storage_type",
            field=models.CharField(
                choices=[("hdfs", "HDFS"), ("redis", "Redis")],
                db_index=True,
                default="redis",
                max_length=32,
                verbose_name="Storage Type",
            ),
        ),
    ]
