# Generated by Django 3.2.18 on 2023-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0009_auto_20230518_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorplugin",
            name="auth_rt",
            field=models.BooleanField(default=False, verbose_name="是否授权"),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="auth_rt",
            field=models.BooleanField(default=False, verbose_name="is RT Authorized"),
        ),
    ]
