# Generated by Django 3.2.23 on 2024-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0010_auto_20230625_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="pull_config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="拉取配置"),
        ),
    ]
