# Generated by Django 3.2.23 on 2024-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0011_auto_20240620_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectorconfig",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="collectorplugin",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="collectorplugin",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="redisconfig",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="redisconfig",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="bkbase_data_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="接入ID"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="bkbase_hdfs_processing_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="BKBase HDFS Processing ID"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="bkbase_hdfs_table_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="BKBase HDFS Table ID"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="bkbase_processing_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="清洗ID"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="bkbase_table_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="入库表"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
    ]
