# Generated by Django 3.2.23 on 2024-07-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0012_auto_20240620_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="pull_type",
            field=models.CharField(
                choices=[("partial", "增量"), ("full", "全量")], default="partial", max_length=16, verbose_name="拉取类型"
            ),
        ),
    ]
