# Generated by Django 3.2.23 on 2024-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0013_snapshot_pull_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="status_msg",
            field=models.TextField(blank=True, null=True, verbose_name="状态信息"),
        ),
    ]
