# Generated by Django 3.2.23 on 2025-03-07 08:51

from django.db import migrations, models


def migrate_snapshotstorage_status(apps, schema_editor):
    Snapshot = apps.get_model('databus', 'Snapshot')
    SnapshotStorage = apps.get_model('databus', 'SnapshotStorage')

    # 获取所有状态为 'running' 的 Snapshot
    running_snapshots = Snapshot.objects.filter(status='running')

    # 更新与 'hdfs' 类型相关的 SnapshotStorage 记录的状态为 'running'
    for snapshot in running_snapshots:
        SnapshotStorage.objects.filter(snapshot=snapshot, storage_type='hdfs').update(status='running')


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0016_auto_20250307_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotstorage',
            name='status',
            field=models.CharField(
                choices=[('closed', '已关闭'), ('running', '运行中'), ('failed', '失败'), ('preparing', '启动中')],
                db_index=True,
                default='closed',
                max_length=32,
                verbose_name='状态',
            ),
        ),
        migrations.RunPython(migrate_snapshotstorage_status),
    ]
