# Generated by Django 3.2.23 on 2025-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0016_auto_20250307_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotstorage',
            name='status',
            field=models.CharField(
                choices=[('closed', '已关闭'), ('running', '运行中'), ('failed', '失败'), ('preparing', '启动中')],
                db_index=True,
                default='closed',
                max_length=32,
                verbose_name='状态',
            ),
        ),
    ]
