# Generated by Django 4.2.19 on 2025-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0017_snapshotstorage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotCheckStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=64)),
                ('resource_type_id', models.CharField(max_length=64)),
                ('join_data_type', models.CharField(max_length=32)),
                ('http_pull_count', models.IntegerField(default=0)),
                ('doris_storage_count', models.IntegerField(default=0)),
                ('hdfs_storage_count', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('system_id', 'resource_type_id', 'join_data_type')},
            },
        ),
    ]
