# Generated by Django 4.2.19 on 2025-03-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0018_snapshotcheckstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorplugin',
            name='has_replica_storage',
            field=models.BooleanField(default=False, verbose_name='是否有副存储'),
        ),
    ]
