# Generated by Django 4.2.25 on 2025-12-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0019_collectorplugin_has_replica_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='record_log_type',
            field=models.CharField(blank=True, choices=[('SDK', 'SDK接入'), ('LOG', 'LOG接入')], max_length=64, verbose_name='记录日志方式'),
        ),
        migrations.AddField(
            model_name='collectorconfig',
            name='select_sdk_type',
            field=models.CharField(blank=True, choices=[('PYTHON_SDK', 'Python SDK'), ('JAVA_SDK', 'JAVA SDK'), ('GO_SDK', 'Go SDK')], max_length=64, verbose_name='SDK类型'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义配置'),
        ),
    ]
