# Generated by Django 4.2.25 on 2025-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0019_collectorplugin_has_replica_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='record_log_type',
            field=models.CharField(blank=True, choices=[('SDK', 'SDK接入'), ('LOG', 'LOG接入')], max_length=64, verbose_name='记录日志方式'),
        ),
        migrations.AddField(
            model_name='collectorconfig',
            name='select_sdk_type',
            field=models.CharField(blank=True, choices=[('PYTHON_SDK', 'PYTHON SDK'), ('JAVA_SDK', 'JAVA SDK'), ('GO_SDK', 'GO SDK')], max_length=64, verbose_name='SDK类型'),
        ),
    ]
