# Generated by Django 4.2.25 on 2025-11-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0020_collectorconfig_record_log_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='is_configuration',
            field=models.BooleanField(default=False, verbose_name='是否配置完成'),
        ),
        migrations.AlterField(
            model_name='collectorconfig',
            name='select_sdk_type',
            field=models.CharField(blank=True, choices=[('PYTHON_SDK', 'Python SDK'), ('JAVA_SDK', 'JAVA SDK'), ('GO_SDK', 'Go SDK')], max_length=64, verbose_name='SDK类型'),
        ),
    ]
