# Generated by Django 4.2.27 on 2026-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0020_snapshot_custom_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='record_log_type',
            field=models.CharField(
                blank=True,
                choices=[('SDK', 'SDK接入'), ('LOG', 'LOG接入')],
                default='SDK',
                max_length=64,
                verbose_name='记录日志方式',
            ),
        ),
        migrations.AddField(
            model_name='collectorconfig',
            name='select_sdk_type',
            field=models.CharField(
                blank=True,
                choices=[('PYTHON_SDK', 'Python SDK'), ('JAVA_SDK', 'JAVA SDK'), ('GO_SDK', 'Go SDK')],
                default='PYTHON_SDK',
                max_length=64,
                verbose_name='SDK类型',
            ),
        ),
    ]
