# Generated by Django 4.2.26 on 2026-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0021_collectorconfig_record_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorconfig',
            name='select_sdk_type',
            field=models.CharField(
                blank=True,
                choices=[('PYTHON_SDK', 'Python SDK'), ('JAVA_SDK', 'Java SDK'), ('GO_SDK', 'Go SDK')],
                default='PYTHON_SDK',
                max_length=64,
                verbose_name='SDK类型',
            ),
        ),
    ]
