# Generated by Django 4.2.25 on 2025-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0021_collectorconfig_is_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义配置'),
        ),
    ]
