"""Generated by Kilo Code for adding error_type field to SnapshotCheckStatistic."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databus", "0022_alter_collectorconfig_select_sdk_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="SnapshotCheckStatistic",
            name="error_type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                verbose_name="失败类型：None=成功，source=源系统拉取失败，storage=存储查询失败",
            ),
        ),
    ]
