# Generated by Django 4.2.25 on 2025-11-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0022_snapshot_custom_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorconfig',
            name='is_configuration',
        ),
    ]
