# Generated by Django 4.2.30 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0023_snapshotcheckstatistic_error_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='redisconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='snapshotcheckstatistic',
            name='error_type',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
