# Generated by Django 3.2.12 on 2023-04-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0003_auto_20230412_1039"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sensitiveobject",
            unique_together=set(),
        ),
    ]
