# Generated by Django 3.2.23 on 2024-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0005_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="action",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="datamap",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="datamap",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="field",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="field",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="globalmetaconfig",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="globalmetaconfig",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="sensitiveobject",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="sensitiveobject",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="system",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="system",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="systemrole",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="systemrole",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
        ),
    ]
