# Generated by Django 3.2.23 on 2025-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_doris_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='is_index',
            field=models.BooleanField(default=False, verbose_name='是否索引'),
        ),
    ]
