# Generated by Django 3.2.23 on 2025-03-07 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_alter_field_is_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='globalmetaconfig',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='globalmetaconfig',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='globalmetaconfig',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='globalmetaconfig',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='sensitiveobject',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sensitiveobject',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='sensitiveobject',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sensitiveobject',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='system',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='system',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='system',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='system',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'),
        ),
    ]
