# Generated by Django 3.2.23 on 2025-03-21 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_auto_20250307_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDiagnosisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('system_id', models.CharField(max_length=64, unique=True, verbose_name='系统ID')),
                ('push_uid', models.CharField(default=None, max_length=64, null=True, verbose_name='系统诊断推送订阅uid')),
                (
                    'push_status',
                    models.CharField(
                        blank=True,
                        choices=[('push', '推送'), ('pause', '暂停')],
                        max_length=32,
                        null=True,
                        verbose_name='系统诊断推送状态',
                    ),
                ),
                ('push_config', models.JSONField(blank=True, default=dict, null=True, verbose_name='系统诊断推送配置')),
                ('push_result', models.JSONField(blank=True, default=dict, null=True, verbose_name='系统诊断推送结果')),
                (
                    'push_error_message',
                    models.TextField(blank=True, default=None, null=True, verbose_name='系统诊断推送错误信息'),
                ),
            ],
            options={
                'verbose_name': '系统诊断',
                'verbose_name_plural': '系统诊断',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='system',
            name='enable_system_diagnosis_push',
            field=models.BooleanField(default=False, verbose_name='是否开启系统诊断推送'),
        ),
    ]
