# Generated by Django 3.2.23 on 2025-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_auto_20250321_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdiagnosisconfig',
            name='push_status',
            field=models.CharField(
                blank=True,
                choices=[('push', '推送'), ('pause', '暂停'), ('failed', '失败')],
                max_length=32,
                null=True,
                verbose_name='系统诊断推送状态',
            ),
        ),
    ]
