# Generated by Django 3.2.23 on 2025-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0011_alter_systemdiagnosisconfig_push_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='system_diagnosis_extra',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='系统诊断额外信息'),
        ),
    ]
