# Generated by Django 4.2.19 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_system_system_diagnosis_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
    ]
