# Generated by Django 4.2.19 on 2025-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_action_resource_type_ids_resourcetype_ancestors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='property',
            field=models.JSONField(default=dict, verbose_name='属性'),
        ),
    ]
