# Generated by Django 4.2.19 on 2025-04-23 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_action_resource_type_ids_resourcetype_ancestors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('scene', models.CharField(help_text='配置场景，标识配置的应用场景', max_length=255)),
                ('config_name', models.CharField(help_text='配置名称，标识配置的名称', max_length=255)),
                ('config_content', models.JSONField(help_text='配置内容，存储具体的配置数据，JSON格式')),
            ],
            options={
                'unique_together': {('scene', 'config_name', 'created_by')},
            },
        ),
    ]
