# Generated by Django 4.2.19 on 2025-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0016_init_system_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='scene',
            field=models.CharField(choices=[('search_config', '搜索配置')], help_text='配置场景，标识配置的应用场景', max_length=255),
        ),
    ]
