# Generated by Django 4.2.19 on 2025-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0017_alter_generalconfig_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='property',
            field=models.JSONField(default=dict, verbose_name='属性'),
        ),
    ]
