# Generated by Django 4.2.23 on 2025-08-06 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_alter_field_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumMappingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Enum Mapping Collection',
                'verbose_name_plural': 'Enum Mapping Collections',
            },
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EnumMappingCollectionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=255)),
                ('related_object_id', models.CharField(max_length=255)),
                ('related_type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Collection to Strategy Relation',
                'verbose_name_plural': 'Collection to Strategy Relations',
                'unique_together': {('collection_id', 'related_object_id', 'related_type')},
            },
        ),
        migrations.CreateModel(
            name='EnumMappingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                (
                    'collection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entities',
                        to='meta.enummappingcollection',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Enum Mapping Entity',
                'verbose_name_plural': 'Enum Mapping Entities',
                'unique_together': {('collection', 'key')},
            },
        ),
    ]
