# Generated by Django 4.2.19 on 2025-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_alter_field_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
