# Generated by Django 4.2.19 on 2025-05-28 03:31
from typing import List

import django.utils.timezone
from django.db import migrations, models

from apps.meta.constants import SystemSourceTypeEnum


def populate_unique_id(apps, schema_editor):
    from apps.meta.models import Action

    action_model: Action = apps.get_model("meta", "Action")
    for action in action_model.objects.all():
        action.unique_id = Action.gen_unique_id(system_id=action.system_id, action_id=action.action_id)
        action.save(update_fields=["unique_id"])


def update_system_audit_status(apps, schema_editor):
    """
    更新审计系统接入状态
    """

    from apps.meta.models import System

    system_ids: List[str] = System.objects.filter(
        source_type__in=[SystemSourceTypeEnum.IAM_V3.value, SystemSourceTypeEnum.IAM_V4.value]
    ).values_list("system_id", flat=True)
    System.bulk_update_system_audit_status(system_ids=system_ids)


class Migration(migrations.Migration):
    dependencies = [
        ('meta', '0018_alter_field_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='audit_status',
            field=models.CharField(
                choices=[('pending', '待接入'), ('accessed', '已接入')], default='pending', max_length=16, verbose_name='审计状态'
            ),
        ),
        migrations.RunPython(update_system_audit_status),
        migrations.AlterField(
            model_name='system',
            name='clients',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='客户端'),
        ),
        migrations.CreateModel(
            name='SystemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('system_id', models.CharField(max_length=64, verbose_name='System ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'System Favorite',
                'verbose_name_plural': 'System Favorite',
                'unique_together': {('system_id', 'username')},
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='resource_type_ids',
        ),
        migrations.CreateModel(
            name='ResourceTypeActionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='创建者'
                    ),
                ),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=32, null=True, verbose_name='修改者'
                    ),
                ),
                ('system_id', models.CharField(db_index=True, max_length=64, verbose_name='系统ID')),
                ('resource_type_id', models.CharField(db_index=True, max_length=64, verbose_name='资源类型ID')),
                ('action_id', models.CharField(db_index=True, max_length=64, verbose_name='操作ID')),
            ],
            options={
                'verbose_name': '资源类型操作关系',
                'verbose_name_plural': '资源类型操作关系',
                'ordering': ['system_id', 'resource_type_id'],
                'unique_together': {('system_id', 'resource_type_id', 'action_id')},
            },
        ),
        migrations.AddField(
            model_name='action',
            name='unique_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='唯一标识'),
        ),
        migrations.RunPython(populate_unique_id),
        migrations.AlterField(
            model_name='action',
            name='unique_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='唯一标识'),
        ),
    ]
