# Generated by Django 4.2.19 on 2025-05-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_alter_field_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetype',
            old_name='ancestors',
            new_name='ancestor',
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='provider_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='资源类型配置'),
        ),
        migrations.CreateModel(
            name='ResourceTypeTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                (
                    'related',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='tree_node', to='meta.resourcetype'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
