# Generated by Django 4.2.19 on 2025-06-03 11:45

from django.db import migrations, models


def forwards_fill_unique_id(apps, schema_editor):
    ResourceType = apps.get_model('meta', 'ResourceType')
    for rt in ResourceType.objects.all():
        rt.unique_id = f"{rt.system_id}:{rt.resource_type_id}"
        rt.save(update_fields=["unique_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0019_rename_ancestors_resourcetype_ancestor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcetype",
            name="unique_id",
            field=models.CharField(
                verbose_name="唯一标识",
                max_length=255,
                unique=True,
                db_index=True,
                null=True,  # 允许临时为空
                blank=True,
            ),
        ),
        migrations.RunPython(forwards_fill_unique_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="resourcetype",
            name="unique_id",
            field=models.CharField(
                verbose_name="唯一标识",
                max_length=255,
                unique=True,
                db_index=True,
            ),
        ),
    ]
