# Generated by Django 4.2.19 on 2025-06-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0019_system_audit_status'),
        ('meta', '0020_resourcetype_unique_id'),
    ]

    operations = []
