# Generated by Django 4.2.19 on 2025-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0021_merge_20250609_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='permission_type',
            field=models.CharField(
                choices=[('simple', '简单权限'), ('complex', '复杂权限')],
                default='complex',
                max_length=16,
                verbose_name='权限类型',
            ),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='unique_id',
            field=models.CharField(
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="唯一标识，资源类型场景下为'{系统ID}:{资源类型ID}'",
            ),
        ),
    ]
