# Generated by Django 4.2.19 on 2025-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0022_system_permission_type_alter_generalconfig_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='permission_type',
            field=models.CharField(
                blank=True,
                choices=[('simple', '简单权限'), ('complex', '复杂权限')],
                default='complex',
                max_length=16,
                null=True,
                verbose_name='权限类型',
            ),
        ),
    ]
