# Generated by Django 4.2.23 on 2025-08-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0019_enummappingcollection_alter_generalconfig_id_and_more'),
        ('meta', '0023_alter_system_permission_type'),
    ]

    operations = []
