# Generated by Django 4.2.23 on 2025-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0024_merge_20250819_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enummappingcollectionrelation',
            name='related_type',
            field=models.CharField(choices=[('strategy', '策略'), ('tool', '工具')], max_length=64),
        ),
    ]
